import type { RequirementDomain } from "../types";

export const rotatingBuilding: RequirementDomain = {
  key: "RB",
  title: "Rotating Building Homepage & Customisation",
  summary:
    "The entry surface for every account: a rotating 3D building with 16 fixed slots, a separate background layer, per-account configuration and advertising slots.",
  coverage:
    "Built from src/lib/homepage/*, src/components/homepage/*, src/pages/homepage/*, src/pages/Backgrounds.tsx, mem://features/homepage-customization and the platform_building_default / building_assets / platform_advertisements tables.",
  requirements: [
    {
      id: "RB-001",
      name: "The building is the landing surface",
      category: "Homepage",
      source: "mem://index.md Core rule",
      requirement: "'/' renders the rotating building for the active workspace; it is never replaced by a dashboard.",
      behaviour: ["Rotating scene renders for every role", "Dashboards are entered from the building"],
      implementation: {
        files: ["src/routes/index.tsx", "src/components/adventures/RotatingAdventureScene.tsx", "src/lib/homepage/useBuildingContext.ts"],
        routes: ["/"],
      },
      dependencies: ["PLAT-002", "WS-001"],
      validation: [{ kind: "route", target: "/" }],
      restorationSource: "current index route",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "RB-002",
      name: "Background layer is separate from the building layer",
      category: "Homepage",
      source: "mem://features/homepage-customization — 'Background vs Building layers'",
      requirement: "Background (image or video) and building are two independent layers; changing one never changes the other.",
      behaviour: ["Background accepts image or video", "Video background loops seamlessly behind the building"],
      implementation: {
        files: [
          "src/pages/homepage/HomepageBackgroundPage.tsx",
          "src/pages/Backgrounds.tsx",
          "src/components/SeamlessBackground.tsx",
          "src/lib/homepage/homepageConfig.ts",
        ],
        routes: ["/homepage/background", "/backgrounds"],
      },
      validation: [{ kind: "route", target: "/backgrounds" }, { kind: "module", target: "src/lib/homepage/homepageConfig.ts" }],
      restorationSource: "src/lib/homepage/homepageConfig.ts (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "RB-003",
      name: "16 fixed building slots",
      category: "Homepage",
      source: "mem://features/homepage-customization — 16 building slots, Replace Building editor",
      requirement:
        "The building exposes exactly 16 fixed slots. A slot may be edited or replaced; the slot count and positions are fixed.",
      behaviour: ["Slot assignment is stored per account/workspace", "Replace Building opens the editor for that slot only"],
      implementation: {
        files: ["src/lib/homepage/buildingSlots.ts", "src/lib/homepage/buildingAssets.ts", "src/components/homepage/BuildingEditGuard.tsx", "src/components/homepage/BuildingVersionSelector.tsx"],
        tables: ["building_assets", "platform_building_default"],
        dbFunctions: ["get_account_homepage_config", "get_org_homepage_config", "get_workspace_homepage_config", "get_platform_free_building"],
      },
      dependencies: ["AST-001"],
      validation: [
        { kind: "module", target: "src/lib/homepage/buildingSlots.ts" },
        { kind: "database", target: "building_assets" },
      ],
      restorationSource: "src/lib/homepage/buildingSlots.ts (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "RB-004",
      name: "Per-account configuration with a platform default",
      category: "Homepage",
      source: "mem://features/homepage-customization — per-account config",
      requirement:
        "Each account may customise its building; accounts with no customisation fall back to the platform default building.",
      behaviour: ["Default is administered centrally", "Customisation is scoped to the workspace, not global"],
      implementation: {
        files: ["src/lib/homepage/defaults.ts"],
        tables: ["platform_building_default"],
        dbFunctions: ["get_platform_free_building"],
      },
      dependencies: ["RB-003", "WS-001"],
      validation: [{ kind: "database", target: "platform_building_default" }],
      restorationSource: "src/lib/homepage/defaults.ts (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "RB-005",
      name: "Advertising slots, none on Pro",
      category: "Homepage",
      source: "Approved in the payments/pricing master prompt: 'Admin controls 8 billboard slots. Pro building has no ads.'",
      requirement: "The building carries 8 administered billboard slots; a Pro workspace's building shows no advertising.",
      behaviour: ["Admin authors the slots", "Entitlement check removes ads for paid plans"],
      implementation: {
        files: ["src/lib/homepage/advertisements.ts", "src/components/ads/AdSenseUnit.tsx"],
        tables: ["platform_advertisements"],
      },
      dependencies: ["PAY-004"],
      validation: [{ kind: "database", target: "platform_advertisements" }, { kind: "module", target: "src/lib/homepage/advertisements.ts" }],
      restorationSource: "src/lib/homepage/advertisements.ts (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "RB-006",
      name: "Uploads reflect on preview",
      category: "Homepage",
      source: "Approved: 'Uploads reflect on preview' (GPL asset uploads used as buildings/backgrounds)",
      requirement: "An uploaded building or background is visible in the preview immediately after upload.",
      behaviour: ["Signed preview URL is used for private storage", "No page reload required"],
      implementation: { files: ["src/lib/homepage/buildingAssets.ts", "src/components/assets"], symbols: ["signed preview"] },
      dependencies: ["AST-003"],
      validation: [{ kind: "behaviour", target: "Upload a building asset and confirm it previews without reloading" }],
      restorationSource: "current asset preview helpers",
      status: "PASS",
      permanent: "PENDING",
    },
  ],
};

export const publicSite: RequirementDomain = {
  key: "SITE",
  title: "Public Marketing Site (CMS)",
  summary: "The cinematic product-led public homepage with editable sections, stats and testimonials.",
  coverage: "Built from src/components/site/*, site_sections / site_stats_settings / site_testimonials tables.",
  requirements: [
    {
      id: "SITE-001",
      name: "13 editable public sections",
      category: "Public site",
      source: "Approved: 'MathGPL public homepage: Cinematic, product-led, 13 editable sections'",
      requirement: "The public homepage is composed of administered sections whose copy and media are editable, not hard-coded.",
      behaviour: ["Sections are ordered and individually toggleable", "Editing does not require a code change"],
      implementation: { files: ["src/components/site"], tables: ["site_sections"] },
      dependencies: ["ADM-001"],
      validation: [{ kind: "database", target: "site_sections" }],
      restorationSource: "site_sections rows (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "SITE-002",
      name: "Live platform stats and testimonials",
      category: "Public site",
      source: "code-evidenced (get_site_stats, site_stats_settings, site_testimonials)",
      requirement: "The public site can show real platform statistics and curated testimonials, both administered.",
      behaviour: ["Stats come from a database function, not typed-in numbers", "Testimonials are curated, publishable rows"],
      implementation: { tables: ["site_stats_settings", "site_testimonials"], dbFunctions: ["get_site_stats"] },
      validation: [{ kind: "database", target: "get_site_stats" }],
      restorationSource: "get_site_stats (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "SITE-003",
      name: "Secret system-access entrance",
      category: "Public site",
      source: "Approved with the platform admin work (secret system-access entrance)",
      requirement: "A non-advertised entrance exists for system access; it must not be discoverable from public navigation.",
      behaviour: ["Not linked in menus", "Still requires full authentication and owner role"],
      implementation: { files: ["src/pages/access/SecretAccessPage.tsx"], routes: ["/access"] },
      dependencies: ["ACCT-005"],
      validation: [{ kind: "module", target: "src/pages/access/SecretAccessPage.tsx" }],
      restorationSource: "src/pages/access/SecretAccessPage.tsx",
      status: "PASS",
      permanent: "PENDING",
    },
  ],
};
