import type { RequirementDomain } from "../types";

export const classes: RequirementDomain = {
  key: "CLS",
  title: "Teaching Hub, Classes & Membership",
  summary: "Classes as containers of members and content, the Teaching Hub shell, rosters and joining.",
  coverage: "Built from src/pages/TeachingHub*.tsx, src/components/class/*, src/components/workspace/WorkspaceShell.tsx and the class_* tables.",
  requirements: [
    {
      id: "CLS-001",
      name: "Workspace shell with Teaching Hub and MathGPL Live tabs",
      category: "Classes",
      source: "Approved: 'Workspace Shell: Teaching Hub and MathGPL Live tabs' + 'Independent Teaching Hub (Class) and MathGPL Live (Session)'",
      requirement:
        "Teaching Hub (classes) and MathGPL Live (sessions) are two independent areas inside one workspace shell; neither depends on the other.",
      behaviour: ["A class works with no live session", "A live session works with no class"],
      implementation: {
        files: ["src/components/workspace/WorkspaceShell.tsx", "src/pages/TeachingHubClasses.tsx", "src/pages/live/LiveHub.tsx"],
        routes: ["/teaching-hub", "/teaching-hub/classes", "/live"],
      },
      dependencies: ["WS-001", "LIVE-001"],
      validation: [{ kind: "route", target: "/teaching-hub/classes" }, { kind: "route", target: "/live" }],
      restorationSource: "WorkspaceShell (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "CLS-002",
      name: "Class content is duplicated in, never linked out",
      category: "Classes",
      source: "mem://features/lesson-note-storage",
      requirement: "Content placed in a class is a class-owned copy; editing it never edits the workspace original.",
      behaviour: ["Class notes, games, galleries and boards are class rows"],
      implementation: { tables: ["class_lesson_notes", "class_games", "class_galleries", "class_smartboard_state", "class_content_nodes", "class_adventure_notes"] },
      dependencies: ["LN-010"],
      validation: [{ kind: "database", target: "class_lesson_notes" }],
      restorationSource: "class_* tables (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "CLS-003",
      name: "Joining a class",
      category: "Classes",
      source: "Approved with the workspace ecosystem work",
      requirement:
        "A student joins via code, invitation or an approved request; joining enrols them in the owning workspace and respects class limits.",
      behaviour: ["Join requests can be approved or declined", "Class and student limits are enforced server-side"],
      implementation: {
        files: ["src/pages/JoinClassPage.tsx"],
        routes: ["/join", "/requests"],
        tables: ["class_members", "class_join_requests", "class_invitations", "class_join_codes"],
        dbFunctions: ["join_class_with_code", "class_member_enrols_workspace", "enforce_class_limit", "enforce_class_student_limit", "get_class_join_request_profiles"],
      },
      dependencies: ["WS-004", "PAY-005"],
      validation: [{ kind: "database", target: "enforce_class_student_limit" }],
      restorationSource: "current join functions",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "CLS-004",
      name: "Premium class layouts, mobile-first",
      category: "Classes",
      source: "Approved: 'Class Layouts: Premium white cards on navy. Mobile-first 44px targets.'",
      requirement: "Class surfaces use the premium card layout with a minimum 44px touch target on mobile.",
      behaviour: ["Cards stack cleanly on small screens", "Controls meet the touch-target minimum"],
      implementation: { files: ["src/pages/class", "src/components/class"] },
      dependencies: ["DES-001"],
      validation: [{ kind: "manual", target: "Review a class page at mobile width" }],
      restorationSource: "current class components",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "CLS-005",
      name: "Teacher management for schools and parents",
      category: "Classes",
      source: "mem://features/account-architecture",
      requirement: "A school manages its teachers and a parent links to their child's teachers, each with its own roster surface.",
      behaviour: ["School invites and removes teachers", "Parent–teacher links are consented, not implicit"],
      implementation: {
        routes: ["/school/teachers", "/family/teachers", "/teacher/students"],
        tables: ["teacher_invitations", "parent_teacher_links", "student_workspace_access"],
        dbFunctions: ["invite_teacher_by_user"],
      },
      dependencies: ["ACCT-006", "WS-005"],
      validation: [{ kind: "route", target: "/school/teachers" }, { kind: "database", target: "teacher_invitations" }],
      restorationSource: "mem://features/account-architecture + current routes",
      status: "PASS",
      permanent: "PENDING",
    },
  ],
};

export const assessment: RequirementDomain = {
  key: "ASMT",
  title: "Assignments, Assessment & Marking",
  summary: "Set work, assessments, the attempt lifecycle, marking and answer keys.",
  coverage: "Built from src/lib/assessment/*, assessments / assessment_progress / assessment_answer_keys / learning_assignments tables.",
  requirements: [
    {
      id: "ASMT-001",
      name: "Assignments cover classwork, homework and set work",
      category: "Assessment",
      source: "Approved: 'Assignment: Set work, classwork and homework'",
      requirement: "A teacher can assign work to a class or a student, with a due date and a completion state per student.",
      behaviour: ["Student sees assigned work in their hub", "Completion is tracked per student"],
      implementation: {
        routes: ["/student/assignments", "/teaching-hub/classes/$classId/assignments"],
        tables: ["learning_assignments", "assessment_progress"],
      },
      dependencies: ["CLS-003"],
      validation: [{ kind: "database", target: "learning_assignments" }],
      restorationSource: "current assignment tables",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "ASMT-002",
      name: "Attempt lifecycle",
      category: "Assessment",
      source: "Approved: 'Fix Attempt Lifecycle'",
      requirement:
        "An attempt has a clear start, working, submitted and marked state. State never leaks between questions or between attempts.",
      behaviour: ["Resuming restores the same attempt", "A new question starts a clean attempt state"],
      implementation: { files: ["src/lib/assessment/createAssessment.ts"], tables: ["assessment_progress", "assessment_board_state", "assessment_question_board_state", "smart_card_attempts"] },
      dependencies: ["FLT-003"],
      validation: [{ kind: "behaviour", target: "Start an attempt, leave, return: same attempt resumes" }],
      restorationSource: "current assessment state tables",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "ASMT-003",
      name: "Marking is derived, per step",
      category: "Assessment",
      source: "Approved: 'Use Floating Number Evaluation for marks' + per-step table marking",
      requirement: "Marks come from evaluated work, awarded step by step, with an answer key stored separately from the student view.",
      behaviour: ["Marks appear as steps complete", "Answer keys are never exposed to students"],
      permissions: ["assessment_answer_keys readable only by the owning teacher/service role"],
      implementation: { tables: ["assessment_answer_keys", "assessment_progress"], files: ["src/lib/floating/verifier.ts"] },
      dependencies: ["FLT-005", "TBL-003"],
      validation: [{ kind: "database", target: "assessment_answer_keys" }, { kind: "manual", target: "Confirm students cannot read answer keys" }],
      restorationSource: "assessment_answer_keys policies (current)",
      status: "PASS",
      permanent: "PENDING",
      severity: "HIGH",
    },
    {
      id: "ASMT-004",
      name: "Mathematical referee before generation",
      category: "Assessment",
      source: "Approved: 'COMPLETE-CONTEXT MATHEMATICAL VALIDATION'",
      requirement:
        "Before generating a solution the complete problem (question, tables, diagram, graphs, Floating Numbers, existing solution) is reasoned over; only a genuine mathematical problem is reported, with issue-specific choices.",
      behaviour: ["Genuine issues are shown with issue-specific actions", "Missing solutions or data held in tables/diagrams never raise an issue"],
      implementation: { files: ["src/lib/lessonnotes/ai/problemReview.ts", "src/components/lessonnotes/ProblemReviewDialog.tsx"] },
      dependencies: ["AI-004"],
      validation: [{ kind: "module", target: "src/lib/lessonnotes/ai/problemReview.ts" }],
      restorationSource: "problemReview.ts + ProblemReviewDialog.tsx (current)",
      status: "PASS",
      permanent: "PENDING",
    },
  ],
};

export const reports: RequirementDomain = {
  key: "RPT",
  title: "Reports & Progress",
  summary: "Student and class reporting, aggregated progress and trend analysis.",
  coverage: "Built from src/components/reports/*, src/pages/student/StudentReportPage.tsx, student_course_progress / player_stats / report_task_results.",
  requirements: [
    {
      id: "RPT-001",
      name: "Student and class reports",
      category: "Reports",
      source: "Approved: 'Reports: Student Progress Bar Chart (Y-axis 0-100%). Class Report shows averages.'",
      requirement: "A student report shows that student's progress 0–100%; a class report shows class averages over the same measures.",
      behaviour: ["Percentages are bounded 0–100", "Class report never exposes another student's identity to students"],
      implementation: {
        files: ["src/components/reports/ProgressBarChart.tsx", "src/pages/student/StudentReportPage.tsx"],
        routes: ["/student/report", "/teaching-hub/classes/$classId/reports"],
        tables: ["report_task_results", "student_course_progress", "player_stats"],
      },
      dependencies: ["CHT-007"],
      validation: [{ kind: "route", target: "/student/report" }, { kind: "database", target: "report_task_results" }],
      restorationSource: "current report components",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "RPT-002",
      name: "Student dashboard is a read-only aggregate",
      category: "Reports",
      source: "Approved: 'Student Dashboard: Read-only hub with aggregated progress'",
      requirement: "The student hub aggregates classes, assignments, adventures, courses and progress without authoring tools.",
      behaviour: ["No create/publish controls", "Everything opens in a student-appropriate view"],
      implementation: { files: ["src/pages/student", "src/routes/student"], routes: ["/student"] },
      dependencies: ["ACCT-007"],
      validation: [{ kind: "route", target: "/student" }],
      restorationSource: "current student pages",
      status: "PASS",
      permanent: "PENDING",
    },
  ],
};

export const adventure: RequirementDomain = {
  key: "ADV",
  title: "Adventure, Timers, Progress & Rewards",
  summary:
    "Adventure games, the separated Progress Bar and Timer systems, video timers, group racing, rewards and the class gallery.",
  coverage:
    "Built from src/components/gamebuilder/*, src/components/adventure*/*, src/lib/games/*, adventure_* / game_* / class_gallery_* tables and mem://features/adventure-group-progress.",
  requirements: [
    {
      id: "ADV-001",
      name: "Progress Bar and Timer are two separate systems",
      category: "Adventure",
      source: "Approved: 'The Progress Bar and Timer must become two completely separate systems… the video is an optional visual mode of the Timer.'",
      requirement:
        "Progress (learning advancement) and Timer (elapsed/remaining time) are independent. Video is a display mode of the Timer only.",
      behaviour: ["Progress does not advance because time passed", "Timer has segmented, fillable and video modes"],
      implementation: {
        files: ["src/components/gamebuilder/ProgressColumn.tsx", "src/components/gamebuilder/SettingsPanel.tsx", "src/lib/games/timerVideo.ts", "src/hooks/useTimeBar.ts"],
        tables: ["game_time_bars"],
      },
      dependencies: ["ADV-003"],
      validation: [{ kind: "module", target: "src/lib/games/timerVideo.ts" }, { kind: "database", target: "game_time_bars" }],
      restorationSource: "decoupled timer/progress implementation (current)",
      status: "PASS",
      permanent: "PENDING",
      severity: "HIGH",
    },
    {
      id: "ADV-002",
      name: "Fixed Time + Learning bars, 10-group mode",
      category: "Adventure",
      source: "mem://features/adventure-group-progress",
      requirement:
        "Each group carries a Time bar and a Learning bar; up to ten groups race, and Adventure racing is distinct from Video Adventure checkpoint qualification.",
      behaviour: ["Ten groups supported", "Checkpoint qualification is separate from race position"],
      implementation: {
        files: ["src/hooks/useAdventureGroups.ts", "src/hooks/useGroupOutcome.ts"],
        tables: ["adventure_groups", "adventure_group_members", "video_adventure_challenges", "video_adventure_runs"],
      },
      validation: [{ kind: "database", target: "adventure_groups" }, { kind: "module", target: "src/hooks/useAdventureGroups.ts" }],
      restorationSource: "mem://features/adventure-group-progress",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "ADV-003",
      name: "Timer settings behaviour",
      category: "Adventure",
      source:
        "Approved corrections (2026-08-25): delete control at the top, no duration preset dropdown, Fill style/Energy hidden in Video mode, Nest preview, and no time overlay inside the video clip.",
      requirement:
        "Timer settings expose a delete control, a free-entry duration field (no preset dropdown), a Nest/Reset preview (segmented advances one segment per step; fillable advances 10% per step), hide Fill style and Energy in Video mode, and the video clip itself draws no clock.",
      behaviour: [
        "Delete is available including for the system time bar.",
        "Duration accepts mm:ss or plain minutes.",
        "Nest preview is editor-only and never affects live sessions or scores.",
        "No 5:00-style overlay is drawn over the timer video.",
      ],
      implementation: {
        files: ["src/components/gamebuilder/SettingsPanel.tsx", "src/components/gamebuilder/TimerVideoView.tsx"],
        symbols: ["timerDisplay"],
      },
      dependencies: ["ADV-001", "ADV-004"],
      validation: [
        { kind: "behaviour", target: "Open Timer settings: delete present, no preset dropdown, Nest preview works" },
        { kind: "behaviour", target: "Switch to Video mode: Fill style and Energy hidden, no clock over the video" },
      ],
      restorationSource: "SettingsPanel + TimerVideoView changes of 2026-08-25 (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "ADV-004",
      name: "Timer video regions and preview",
      category: "Adventure",
      source: "Approved: 'the preview for the video timer is all zero… it's not editable' → metadata-aware regions and working preview",
      requirement:
        "A timer video exposes intro/loop/outro regions seeded from the real video duration, clamped editable fields, and a preview that seeks, plays and stops reliably.",
      behaviour: [
        "Duration is read from loadedmetadata and durachange, not assumed.",
        "Regions seed to thirds when duration first becomes known.",
        "Preview waits for metadata, seeks, plays, and offers Stop.",
      ],
      implementation: { files: ["src/components/gamebuilder/TimerVideoTimeline.tsx"] },
      dependencies: ["ADV-005"],
      validation: [{ kind: "behaviour", target: "Upload a 15s timer video and confirm regions are non-zero and preview plays" }],
      restorationSource: "TimerVideoTimeline changes of 2026-08-25 (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "ADV-005",
      name: "Every upload offers device and GPL assets",
      category: "Adventure",
      source: "Approved: 'upload timer video should have two options, from file or my GPL assets'",
      requirement:
        "Any media upload control offers both 'My device' and 'My GPL assets'; it must never jump straight to the device file picker.",
      behaviour: ["GPL picker browses by session/sub-session", "Storage paths, external URLs and signed previews all work"],
      implementation: {
        files: [
          "src/components/gamebuilder/TimerVideoTimeline.tsx",
          "src/components/gamebuilder/AssetsPanel.tsx",
          "src/components/lessonnotes/slides/SlidePanel.tsx",
          "src/components/lessonnotes/slides/MyGplMediaPicker.tsx",
        ],
      },
      dependencies: ["AST-004"],
      validation: [{ kind: "behaviour", target: "Open any media upload and confirm both sources are offered" }],
      restorationSource: "MyGplMediaPicker integration (current)",
      status: "PASS",
      severity: "MEDIUM",
      permanent: "PENDING",
      notes:
        "Scope recorded 2026-08-25: every scene/media upload that the GPL library can serve — timer video, slide media and all four game asset kinds (background, reward, progress bar, effect) — offers both 'My device' and 'My GPL assets'. Deliberately device-only, because the GPL library holds image/video only: narration and sound-effect audio, profile avatars, notebook scans and AI intake documents.",
    },
    {
      id: "ADV-006",
      name: "Video adventure with loop checkpoints",
      category: "Adventure",
      source: "Approved: 'Adventure 2.0: Video backgrounds with loop checkpoints'",
      requirement: "A scene can use a looping video background with authored checkpoints that gate progression.",
      behaviour: ["Loop plays seamlessly", "Checkpoint qualification is recorded per run"],
      implementation: {
        files: ["src/components/adventure/VideoBackgroundLayer.tsx"],
        tables: ["adventure_scenes", "adventure_scene_questions", "video_adventure_runs"],
      },
      dependencies: ["ADV-002"],
      validation: [{ kind: "database", target: "video_adventure_runs" }],
      restorationSource: "VideoBackgroundLayer (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "ADV-007",
      name: "Progress → Reward → Gallery chain",
      category: "Adventure",
      source: "Approved: 'Link Adventure-Progress Bar-Reward-Gallery'",
      requirement: "Completing adventure progress issues a reward, and the reward appears in the class/member gallery.",
      behaviour: ["Awards are rows, not UI-only", "Gallery shows earned items per member"],
      implementation: { tables: ["class_gallery_rewards", "class_gallery_awards", "member_gallery_items", "class_galleries"], routes: ["/student/gallery"] },
      dependencies: ["ADV-002"],
      validation: [{ kind: "database", target: "class_gallery_awards" }, { kind: "route", target: "/student/gallery" }],
      restorationSource: "current gallery tables",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "ADV-008",
      name: "Transparent media blends into the scene",
      category: "Adventure",
      source:
        "Approved correction: 'it's supposed to blend with the screen, not black background… when I remove background it should blend anywhere I place it'",
      requirement:
        "Background removal produces straight-alpha transparent media that composites onto any scene with no black or white plate behind it.",
      behaviour: [
        "No wrapper background is drawn around a chroma video.",
        "Straight alpha output with premultipliedAlpha: false.",
        "Non-keyable video falls back to the original rather than breaking.",
      ],
      implementation: { files: ["src/lib/games/videoChromaCut.ts", "src/components/games/ChromaVideo.tsx", "src/components/gamebuilder/TimerVideoView.tsx"] },
      dependencies: ["AST-005"],
      validation: [{ kind: "behaviour", target: "Place processed media over a coloured scene and inspect the corners" }],
      restorationSource: "videoChromaCut straight-alpha change (current)",
      status: "PASS",
      severity: "MEDIUM",
      permanent: "PENDING",
      notes:
        "Scope recorded 2026-08-25: the current pipeline produces straight-alpha output for every asset it processes. Media processed before that change is deliberately left untouched (no bulk reprocessing job) — re-upload is the intended remedy for an old asset that still shows a plate.",
    },
    {
      id: "ADV-009",
      name: "Live adventure sessions",
      category: "Adventure",
      source: "code-evidenced (adventure_live_sessions, useAdventureHeartbeat)",
      requirement: "An adventure can run live with a heartbeat, so disconnects are detected and group state stays current.",
      behaviour: ["Heartbeat updates presence", "Stale sessions are recoverable"],
      implementation: { files: ["src/hooks/useAdventureHeartbeat.ts"], tables: ["adventure_live_sessions"] },
      dependencies: ["STAB-003"],
      validation: [{ kind: "database", target: "adventure_live_sessions" }],
      restorationSource: "current live session tables",
      status: "PASS",
      permanent: "PENDING",
    },
  ],
};

export const courses: RequirementDomain = {
  key: "CRS",
  title: "Courses",
  summary: "Course builder, sections/blocks, exercise questions, assignment to classes and student progress.",
  coverage: "Built from src/pages/CourseBuilderLibrary.tsx, src/components/coursebuilder/*, courses / course_sections / course_blocks tables.",
  requirements: [
    {
      id: "CRS-001",
      name: "Course builder",
      category: "Courses",
      source: "Approved: 'Course Builder'",
      requirement: "A teacher builds a course from ordered sections and blocks, including exercise questions.",
      behaviour: ["Sections and blocks are reorderable", "Exercise questions belong to a course"],
      implementation: {
        files: ["src/pages/CourseBuilderLibrary.tsx", "src/components/coursebuilder"],
        routes: ["/courses", "/course-builder"],
        tables: ["courses", "course_sections", "course_blocks", "course_exercise_questions"],
      },
      validation: [{ kind: "database", target: "course_blocks" }],
      restorationSource: "current course tables",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "CRS-002",
      name: "Course assignment and student progress",
      category: "Courses",
      source: "code-evidenced (class_course_assignments, student_course_progress)",
      requirement: "A course is assigned to a class with per-class settings, and each student's progress is tracked.",
      behaviour: ["Student runner resumes where they stopped"],
      implementation: {
        files: ["src/pages/student/StudentCourseRunnerPage.tsx"],
        routes: ["/student/courses"],
        tables: ["class_course_assignments", "class_course_settings", "student_course_progress"],
      },
      dependencies: ["CRS-001", "RPT-001"],
      validation: [{ kind: "route", target: "/student/courses" }, { kind: "database", target: "student_course_progress" }],
      restorationSource: "current course progress tables",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "CRS-003",
      name: "Video-link versus premium-video courses",
      category: "Courses",
      source: "mem://features/gateway-pricing (gateway items course_video_link, course_premium_video)",
      requirement:
        "Courses distinguish externally linked video from platform-hosted premium video, and the gateway can grant access to each separately.",
      behaviour: ["Premium video is access-gated", "External link courses need no hosting"],
      implementation: { files: ["src/lib/gateway/items.ts"], symbols: ["course_video_link", "course_premium_video"] },
      dependencies: ["GW-001"],
      validation: [{ kind: "module", target: "src/lib/gateway/items.ts", expects: ["course_premium_video"] }],
      restorationSource: "src/lib/gateway/items.ts (current)",
      status: "PASS",
      permanent: "PENDING",
    },
  ],
};

export const live: RequirementDomain = {
  key: "LIVE",
  title: "MathGPL Live & Smart Cards",
  summary: "Online teaching sessions, join codes, broadcast links and public Smart Card publishing.",
  coverage: "Built from src/pages/live/*, src/components/smartcards/*, sessions / smart_cards tables and mem://features/mathgpl-live, mem://features/smart-cards.",
  requirements: [
    {
      id: "LIVE-001",
      name: "Session management with join codes",
      category: "Live",
      source: "mem://features/mathgpl-live — '/live online-teaching hub; Session wraps a hidden class row'",
      requirement:
        "A live session is created from /live, wraps a hidden class row, and students join with a session code. It is independent of the Teaching Hub.",
      behaviour: ["Session code lookup resolves one session", "Session works without an existing class"],
      implementation: {
        files: ["src/pages/live/LiveHub.tsx", "src/pages/live/JoinSessionPage.tsx", "src/pages/live/SessionPickerPage.tsx"],
        routes: ["/live", "/live/join", "/live/sessions"],
        tables: ["sessions"],
        dbFunctions: ["generate_session_code", "lookup_session_by_code", "my_session_code"],
      },
      dependencies: ["CLS-001"],
      validation: [{ kind: "route", target: "/live" }, { kind: "database", target: "lookup_session_by_code" }],
      restorationSource: "mem://features/mathgpl-live + current session functions",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "LIVE-002",
      name: "Broadcast platform links",
      category: "Live",
      source: "Archived plan: 'broadcast platforms for live sessions'",
      requirement: "A session can carry links to external broadcast platforms without the platform hosting the stream.",
      behaviour: ["Link is stored on the session", "No stream hosting is implied"],
      implementation: { tables: ["sessions"] },
      validation: [{ kind: "database", target: "sessions" }],
      restorationSource: ".lovable/plan-broadcast-platforms-for-live-sessions-2026-07-29.md",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "LIVE-003",
      name: "Smart Cards are Live-only publishing",
      category: "Live",
      source: "mem://features/smart-cards + approved: 'Smart Card Publishing at /c/:slug'",
      requirement:
        "A solved question can be published from Live as a public Smartboard challenge at /c/:slug, with a working social preview.",
      behaviour: ["Public page renders without sign-in", "Link preview is generated for the card", "Creator-only controls stay creator-only"],
      implementation: {
        files: ["src/components/smartcards", "supabase/functions/smart-card-preview/index.ts"],
        routes: ["/c/$slug"],
        tables: ["smart_cards", "smart_card_attempts", "smart_card_game_results", "smart_card_presence"],
        dbFunctions: ["generate_share_code", "my_share_code"],
      },
      dependencies: ["LIVE-001"],
      validation: [{ kind: "route", target: "/c/$slug" }, { kind: "database", target: "smart_cards" }],
      restorationSource:
        ".lovable/plan-smart-card-link-preview-public-launch-pipeline-2026-07-29.md + .lovable/plan-fix-the-smart-card-link-pipeline-404-working-public-page-2026-07-29.md",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "LIVE-004",
      name: "Smart Card challenge presentation",
      category: "Live",
      source: "Archived plans: 'put the smart card in the middle', 'automatic creator view', 'share card view on the challenge dashboard (creator only)'",
      requirement: "The challenge view centres the card, opens automatically in creator view for its creator, and shows share controls to the creator only.",
      behaviour: ["Non-creators never see share/admin controls"],
      implementation: { files: ["src/components/smartcards"], routes: ["/c/$slug"] },
      dependencies: ["LIVE-003"],
      validation: [{ kind: "manual", target: "Open a card as creator and as a stranger and compare controls" }],
      restorationSource: ".lovable/plan-share-card-view-on-the-challenge-dashboard-creator-only-2026-07-29.md",
      status: "PASS",
      permanent: "PENDING",
    },
  ],
};

export const community: RequirementDomain = {
  key: "COMM",
  title: "MathGPL Community",
  summary: "A read-only mirror of workspaces with copy-to-my-workspace, discoverable profiles and shared classes.",
  coverage: "Built from src/pages/community/*, src/components/community/*, community_* tables and mem://features/mygpl-community.",
  requirements: [
    {
      id: "COMM-001",
      name: "Community is read-only with explicit copying",
      category: "Community",
      source: "mem://features/mygpl-community",
      requirement:
        "/community mirrors the rotating-building workspace read-only. Using someone's resource means copying it into your own workspace; shared classes require Request Access.",
      behaviour: ["No in-place editing of another workspace", "Copy creates an independent row in the copier's workspace"],
      implementation: {
        files: ["src/pages/community/CommunityHome.tsx", "src/pages/community/CommunityHubPage.tsx", "src/components/community/CommunityModeProvider.tsx"],
        routes: ["/community", "/community/$section"],
        tables: ["community_resources", "community_downloads", "community_profiles", "community_likes", "community_reports"],
        dbFunctions: ["is_community_published", "discover_accounts", "discover_schools"],
      },
      dependencies: ["WS-001"],
      validation: [{ kind: "route", target: "/community" }, { kind: "database", target: "community_resources" }],
      restorationSource: "mem://features/mygpl-community + current community tables",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "COMM-002",
      name: "Discoverable profiles and moderation",
      category: "Community",
      source: "Approved: 'Community Mode: Discoverable profiles and shared assets'",
      requirement: "A workspace chooses whether it is discoverable; published resources can be liked and reported.",
      behaviour: ["Opt-in discoverability", "Reports are stored for review"],
      implementation: { tables: ["community_profiles", "community_likes", "community_reports"] },
      dependencies: ["COMM-001"],
      validation: [{ kind: "database", target: "community_reports" }],
      restorationSource: "current community tables",
      status: "PASS",
      permanent: "PENDING",
    },
  ],
};
