import type { RequirementDomain } from "../types";

export const geometry2d: RequirementDomain = {
  key: "GEO",
  title: "2D Geometry Editor",
  summary:
    "One construction-based diagram engine: points, lines, circles, curves, selection-driven properties, undo and rendering.",
  coverage:
    "Built from src/lib/geometry/scene.ts, src/lib/geometry/editor/*, src/lib/geometry/construct/*, src/components/lessonnotes/geometry-editor/* and src/components/lessonnotes/GeometryDiagram.tsx.",
  requirements: [
    {
      id: "GEO-001",
      name: "One diagram engine, one representation, one renderer",
      category: "Geometry 2D",
      source: "Approved: 'One diagram engine. One mathematical representation. One renderer.'",
      requirement:
        "All diagrams use a single scene model (GeometryScene of GeoObjects) and a single renderer. No parallel drawing system may be added for any feature, including Geometry Properties.",
      behaviour: [
        "GeometryScene = { bounds, objects, meta? }.",
        "Every editor mutation goes through src/lib/geometry/editor/sceneOps.ts.",
        "GeometryDiagram is the only renderer for note/board display.",
      ],
      implementation: {
        files: [
          "src/lib/geometry/scene.ts",
          "src/lib/geometry/editor/sceneOps.ts",
          "src/components/lessonnotes/GeometryDiagram.tsx",
          "src/components/lessonnotes/geometry-editor/GeometryCanvas.tsx",
        ],
        symbols: ["GeometryScene", "GeoObject", "EMPTY_SCENE"],
      },
      validation: [
        { kind: "module", target: "src/lib/geometry/scene.ts", expects: ["EMPTY_SCENE", "GeometryScene"] },
        { kind: "test", target: "src/lib/geometry/__tests__/area.test.ts" },
      ],
      restorationSource: "src/lib/geometry/scene.ts + editor/sceneOps.ts (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "GEO-002",
      name: "Construction-based engine (no sketch approximation)",
      category: "Geometry 2D",
      source:
        "Approved: '2D Diagrams must use the mathematical construction engine' and 'upgrade the 2D engine to purely construction-based (SVG)'",
      requirement:
        "Diagrams are constructed deterministically from mathematical relations and emitted as SVG. AI may propose a construction, never freehand coordinates that only look right.",
      behaviour: ["Deterministic primitives and label placement", "Same input produces the same diagram"],
      implementation: { files: ["src/lib/geometry/construct"], symbols: ["construct primitives"] },
      dependencies: ["AI-004"],
      validation: [{ kind: "module", target: "src/lib/geometry/construct" }],
      restorationSource: "src/lib/geometry/construct/* (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "GEO-003",
      name: "Continuous lines through many points",
      category: "Geometry 2D",
      source: "Regression fix approved: 'line is disconnected. Line's supposed to connect… if I create 100 points, the line's supposed to run through.'",
      requirement: "The line tool builds a continuous polyline: each new point chains to the previous one without breaks.",
      behaviour: ["No orphaned segments", "Chaining continues indefinitely until the tool is changed"],
      implementation: {
        files: ["src/components/lessonnotes/geometry-editor/GeometryCanvas.tsx", "src/lib/geometry/editor/useGeometryEditor.ts"],
        symbols: ["ensurePoint", "addSegment"],
      },
      dependencies: ["GEO-005"],
      validation: [{ kind: "behaviour", target: "Click ten points with the line tool; expect nine connected segments" }],
      restorationSource: "polyline chaining fix in GeometryCanvas (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "GEO-004",
      name: "Two-click circle: centre then circumference",
      category: "Geometry 2D",
      source:
        "Approved: 'Circle construction needs center and circumference points. Dragging center moves circle; dragging circumference point resizes radius. Dots must be removable.'",
      requirement:
        "A circle is created by clicking its centre then a circumference point. Dragging the centre moves it; dragging the circumference point changes the radius; either dot can be removed.",
      behaviour: ["Radius is defined by a real point, not a hidden number", "Circle splits into sub-segments at points on it"],
      implementation: { files: ["src/components/lessonnotes/geometry-editor/GeometryCanvas.tsx", "src/lib/geometry/editor/sceneOps.ts"] },
      validation: [{ kind: "behaviour", target: "Two clicks produce a circle; drag the circumference point to resize" }],
      restorationSource: "two-click circle construction (restored 2026-08)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "GEO-005",
      name: "Commit race must not wipe pending ids",
      category: "Geometry 2D",
      source: "Regression fix approved during the '2D refresh' work",
      requirement:
        "apply()/commit() return the resulting scene so the next click chains off fresh ids; a commit must never clear pendingIds mid-construction.",
      behaviour: ["Rapid clicking does not lose points", "Multi-click tools survive an autosave commit"],
      implementation: { files: ["src/lib/geometry/editor/useGeometryEditor.ts"], symbols: ["apply", "commit", "pendingIds"] },
      validation: [{ kind: "module", target: "src/lib/geometry/editor/useGeometryEditor.ts", expects: ["pendingIds"] }],
      restorationSource: "useGeometryEditor commit-race fix (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "GEO-006",
      name: "Selection drives properties",
      category: "Geometry 2D",
      source:
        "Approved: 'Selection shows properties' + rules 2-lines→Angle, 1-line→Distance, enclosed surface→Angle/Area/Shading",
      requirement:
        "Selecting geometry offers exactly the properties that selection can carry: one line → distance; two lines → angle; an enclosed surface → area/shading.",
      behaviour: ["No irrelevant property controls for a selection", "Properties live in the right-hand panel only"],
      implementation: {
        files: [
          "src/components/lessonnotes/geometry-editor/SelectionInspector.tsx",
          "src/components/lessonnotes/geometry-editor/DiagramToolsPanel.tsx",
          "src/components/lessonnotes/geometry-editor/GeometryModeContext.tsx",
        ],
      },
      dependencies: ["DES-002"],
      validation: [{ kind: "behaviour", target: "Select two lines; only angle properties should be offered" }],
      restorationSource: "SelectionInspector + DiagramToolsPanel (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "GEO-007",
      name: "Everything in the diagram is editable",
      category: "Geometry 2D",
      source: "Approved: 'Make everything in the diagram editable (hundred percent)'",
      requirement: "Static labels are liberated into draggable, editable objects; there is no un-editable baked-in text.",
      behaviour: ["Labels can be moved, retyped and rotated", "Unreferenced point labels hide automatically"],
      implementation: {
        files: ["src/lib/geometry/editor/liberateLabels.ts", "src/lib/geometry/editor/relevance.ts"],
        symbols: ["liberateLabels", "relevance"],
      },
      validation: [{ kind: "module", target: "src/lib/geometry/editor/liberateLabels.ts" }],
      restorationSource: "liberateLabels.ts + relevance.ts (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "GEO-008",
      name: "Diagram edits participate in document undo",
      category: "Geometry 2D",
      source: "Approved: 'FIX DIAGRAM UNDO + QUESTION/DIAGRAM ALIGNMENT'",
      requirement: "A diagram change is a step in the lesson-note history: undo/redo in the document undoes the diagram edit.",
      behaviour: ["Ctrl+Z after a diagram edit reverses that edit", "Undo does not jump past unrelated text edits"],
      implementation: { files: ["src/components/lessonnotes/GeometryDiagram.tsx", "src/components/lessonnotes/DocumentEditor.tsx"] },
      validation: [{ kind: "behaviour", target: "Draw a line, press undo, expect the line to disappear" }],
      restorationSource: "ProseMirror history integration (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "GEO-009",
      name: "Textbook stroke density and typography",
      category: "Geometry 2D",
      source: "Approved: 'precise textbook stroke density' then corrected: 'rectify diagram typography (too thick)'",
      requirement: "Stroke weights are scale-aware and text weight is normal textbook weight — never heavy or blurred at zoom.",
      behaviour: ["Stroke weight adapts to diagram scale", "Labels stay legible dark ink at all zoom levels"],
      implementation: { files: ["src/components/lessonnotes/GeometryDiagram.tsx"] },
      dependencies: ["DIAG-003", "DES-001"],
      validation: [{ kind: "manual", target: "Zoom a diagram and inspect stroke and text weight" }],
      restorationSource: "scale-aware stroke weight change (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "GEO-010",
      name: "Transparent diagram background",
      category: "Geometry 2D",
      source: "Approved with smartboard tool integration ('Transparent background for Geometry')",
      requirement: "A geometry diagram renders on a transparent background so it composites on note and board surfaces.",
      behaviour: ["No opaque white plate behind a diagram"],
      implementation: { files: ["src/components/lessonnotes/GeometryDiagram.tsx"] },
      validation: [{ kind: "manual", target: "Place a diagram over a coloured board and confirm no white plate" }],
      restorationSource: "current renderer",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "GEO-011",
      name: "Workbench versus committed diagram",
      category: "Geometry 2D",
      source: "Approved: 'Workbench vs Committed Diagram lifecycle' (smartboard tool integration)",
      requirement:
        "A diagram is drafted in a workbench and explicitly committed into the lesson/board; an uncommitted workbench never appears to students.",
      behaviour: ["Workbench is teacher-only", "Commit produces the permanent lesson object"],
      implementation: { files: ["src/components/smartboard/GeometryWorkbench.tsx"] },
      dependencies: ["DIAG-001"],
      validation: [{ kind: "module", target: "src/components/smartboard/GeometryWorkbench.tsx" }],
      restorationSource: "GeometryWorkbench (current)",
      status: "PASS",
      permanent: "PENDING",
    },
  ],
};

export const area: RequirementDomain = {
  key: "AREA",
  title: "Area Tool & Regions (2D/Area)",
  summary:
    "Creating a filled region: by manual trace (straight or curved) on the left toolbox, and by picking enclosing lines from the right-hand Diagram Tools panel.",
  coverage:
    "Built from src/lib/geometry/editor/sceneOps.ts (addRegion, addCurvedRegion), regions.ts (cycleFromSegments), boundary.ts (regionEdgesToPath), GeometryCanvas.tsx cases 'addArea' and 'smartArea', GeometryToolbox.tsx, DiagramToolsPanel.tsx, GeometryModeContext.tsx, GeometryDiagram.tsx region rendering, plus the archived plan 'Right-hand Add Area — configuration first, then region pick'. Engine layer is validated by src/lib/geometry/__tests__/area.test.ts (6 tests, PASS on 2026-08-25). Pointer/UI layer is NOT automatically validated.",
  requirements: [
    {
      id: "AREA-001",
      name: "Two independent Area entrances",
      category: "Area",
      source:
        "Archived plan 'Right-hand Add Area — configuration first, then region pick' (2026-08-15), which states the left-hand geometry toolbox stays exactly as it is.",
      requirement:
        "Area is reachable two ways and they stay independent: the left-hand toolbox tool 'addArea' (manual trace) and the right-hand Diagram Tools 'smartArea' (pick enclosing lines). Changes to one must not alter the other.",
      behaviour: [
        "GeometryToolbox exposes addArea with its own draft seeding.",
        "DiagramToolsPanel exposes smartArea with its own workflow card.",
        "GeometryCanvas keeps separate switch cases for the two tools.",
      ],
      implementation: {
        files: [
          "src/components/lessonnotes/geometry-editor/GeometryToolbox.tsx",
          "src/components/lessonnotes/geometry-editor/DiagramToolsPanel.tsx",
          "src/components/lessonnotes/geometry-editor/GeometryCanvas.tsx",
          "src/components/lessonnotes/geometry-editor/GeometryModeContext.tsx",
        ],
        symbols: ["addArea", "smartArea"],
      },
      validation: [
        { kind: "module", target: "src/components/lessonnotes/geometry-editor/GeometryCanvas.tsx", expects: ["case \"addArea\"", "case \"smartArea\""] },
      ],
      restorationSource: ".lovable/plan/right-hand-add-area-configuration-first-then-region-pick-2026-08-15.md",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "AREA-002",
      name: "Manual straight trace creates a filled region",
      category: "Area",
      source: "Approved: 'Tools: Add Text/Distance/Angle/Area. Area Trace: Straight/Curve. Fill/Opacity controls.'",
      requirement:
        "With the Area tool in straight mode, each click adds a boundary point; closing the trace creates one region object carrying the chosen fill colour and opacity.",
      behaviour: [
        "A boundary of fewer than three points creates nothing.",
        "The region stores per-edge geometry so the fill can be drawn.",
        "Temporary points created only for the trace are cleaned up on finalise.",
      ],
      implementation: {
        files: ["src/lib/geometry/editor/sceneOps.ts", "src/components/lessonnotes/geometry-editor/GeometryCanvas.tsx"],
        symbols: ["addRegion", "finalizeSession", "trackSessionPoint"],
      },
      dependencies: ["GEO-001"],
      validation: [
        { kind: "test", target: "src/lib/geometry/__tests__/area.test.ts", expects: ["AREA-002 — manual straight trace creates a filled region"] },
      ],
      restorationSource: "src/lib/geometry/editor/sceneOps.ts addRegion (validated by test, PASS)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "AREA-003",
      name: "Curved trace creates a curved region",
      category: "Area",
      source: "Approved: 'Area Trace: Straight/Curve'",
      requirement:
        "In curve mode, points are grouped in overlapping triplets so every three clicks draw a curve through the middle point, and the closed trace becomes a curved region.",
      behaviour: ["Curve objects are added alongside the region", "The region path follows the curved edges when rendered"],
      implementation: {
        files: ["src/lib/geometry/editor/sceneOps.ts", "src/lib/geometry/editor/boundary.ts"],
        symbols: ["addCurvedRegion", "regionEdgesToPath"],
      },
      dependencies: ["AREA-002"],
      validation: [
        { kind: "test", target: "src/lib/geometry/__tests__/area.test.ts", expects: ["AREA-003 — curved trace creates a curved region"] },
      ],
      restorationSource: "sceneOps.addCurvedRegion (validated by test, PASS)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "AREA-004",
      name: "Enclosed region from picked boundary lines",
      category: "Area",
      source: "Approved: 'Enclosed-surface-to-Angle/Area/Shading' + the right-hand Add Area plan",
      requirement:
        "In smartArea, clicks pick existing straight lines. The region is created only when the picked lines form one simple closed cycle; an open or incomplete chain creates nothing.",
      behaviour: [
        "Every boundary vertex must have degree two for the cycle to close.",
        "Clicking a non-line shows the hint 'Click the straight lines that enclose the region.'",
        "On success the tool ends and the new region becomes the selection.",
      ],
      implementation: {
        files: ["src/lib/geometry/editor/regions.ts", "src/components/lessonnotes/geometry-editor/GeometryCanvas.tsx"],
        symbols: ["cycleFromSegments", "finishTool"],
      },
      dependencies: ["AREA-002", "GEO-006"],
      validation: [
        { kind: "test", target: "src/lib/geometry/__tests__/area.test.ts", expects: ["AREA-004 — enclosed region from picked boundary lines"] },
        { kind: "behaviour", target: "Pick the three sides of a triangle in the right-hand panel and expect a filled region" },
      ],
      restorationSource: "regions.cycleFromSegments (validated by test, PASS)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "AREA-005",
      name: "Chosen colour and density are applied by every close path",
      category: "Area",
      source:
        "Approved in the right-hand Add Area plan: 'Changing them before the pick changes what the created region gets' and 'region filled with the chosen colour + density'.",
      requirement:
        "Whichever way a trace is closed — clicking the first point, double-clicking, or pressing Enter — the created region must carry the teacher's chosen fill colour and density, and the workflow must close with the region selected.",
      behaviour: [
        "Close-on-first-point applies fill and opacity, then finalises the session.",
        "Double-click close applies the same fill and opacity.",
        "Enter close applies the same fill and opacity.",
        "After any close the region is the selection so its properties are editable.",
      ],
      implementation: {
        files: [
          "src/lib/geometry/editor/closeTrace.ts",
          "src/components/lessonnotes/geometry-editor/GeometryCanvas.tsx",
        ],
        symbols: ["closeAreaTrace", "closeTraceNow", "finalizeSession"],
      },
      dependencies: ["AREA-002", "AREA-003"],
      validation: [
        {
          kind: "behaviour",
          target:
            "Choose a non-default fill and density, trace a region, close it by double-click and then by Enter; both must use the chosen values",
        },
        { kind: "module", target: "src/lib/geometry/editor/closeTrace.ts", expects: ["closeAreaTrace"] },
        { kind: "module", target: "src/components/lessonnotes/geometry-editor/GeometryCanvas.tsx", expects: ["closeTraceNow(pendingIds)"] },
        { kind: "test", target: "src/lib/geometry/__tests__/closeTrace.test.ts" },
      ],
      restorationSource:
        ".lovable/plan/right-hand-add-area-configuration-first-then-region-pick-2026-08-15.md (approved behaviour) + src/lib/geometry/editor/closeTrace.ts, the single shared close implementation",
      status: "PASS",
      severity: "MEDIUM",
      permanent: "PENDING",
      notes:
        "Repaired and proven: all three close gestures (first-point click, double-click, Enter) now call one shared closeTraceNow, which delegates to closeAreaTrace with the chosen fill and density, finalises the session and finishes with the new region selected. src/lib/geometry/__tests__/closeTrace.test.ts covers straight and curve mode fill/density, the returned selectable region id and the under-three-points refusal (4 tests passing).",
    },
    {
      id: "AREA-006",
      name: "Unfinished Area picks are discarded on tool change",
      category: "Area",
      source: "Approved in the right-hand Add Area plan, point 4",
      requirement:
        "Starting another tool or cancelling clears an unfinished Area pick: picked lines are dropped and no partial region is left behind.",
      behaviour: ["Changing away from smartArea clears pendingIds", "Escape clears the pending trace"],
      implementation: { files: ["src/components/lessonnotes/geometry-editor/GeometryCanvas.tsx"], symbols: ["setPendingIds"] },
      validation: [
        { kind: "module", target: "src/components/lessonnotes/geometry-editor/GeometryCanvas.tsx", expects: ["if (prev === \"smartArea\") setPendingIds([])"] },
        { kind: "behaviour", target: "Pick two lines, switch tool, confirm nothing is created and no picks remain" },
      ],
      restorationSource: "the tool-change effect in GeometryCanvas (~line 124, current)",
      status: "PASS",
      permanent: "PENDING",
      notes:
        "Verified for smartArea. The equivalent clear for an unfinished manual addArea trace was not confirmed in this pass — see the regression report.",
    },
    {
      id: "AREA-007",
      name: "Regions render in note, board and export",
      category: "Area",
      source: "code-evidenced; implied by every diagram surface requirement",
      requirement:
        "A region renders from its stored per-edge geometry, with a polygon fallback for legacy regions created before edges were stored.",
      behaviour: ["Fill and opacity render as authored", "Legacy regions still draw"],
      implementation: { files: ["src/components/lessonnotes/GeometryDiagram.tsx", "src/lib/geometry/editor/boundary.ts"], symbols: ["regionEdgesToPath"] },
      dependencies: ["GEO-001"],
      validation: [{ kind: "test", target: "src/lib/geometry/__tests__/area.test.ts", expects: ["stores per-edge geometry so the fill can be drawn"] }],
      restorationSource: "GeometryDiagram region rendering (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "AREA-008",
      name: "Delete Diagram and region deletion",
      category: "Area",
      source: "Approved: 'Add Delete Diagram and Fill/Opacity controls'",
      requirement: "A diagram can be deleted outright, and an individual region can be removed without destroying its boundary lines.",
      behaviour: ["Deleting a region leaves the lines", "Delete Diagram removes the whole object from the note"],
      implementation: { files: ["src/components/lessonnotes/geometry-editor/SelectionInspector.tsx", "src/lib/geometry/editor/sceneOps.ts"] },
      validation: [
        { kind: "behaviour", target: "Delete a region and confirm its boundary lines remain" },
        { kind: "test", target: "src/lib/geometry/__tests__/regionDelete.test.ts" },
      ],
      restorationSource: "current sceneOps delete path",
      status: "PASS",
      severity: "LOW",
      permanent: "PENDING",
      notes:
        "Cleared 2026-08-25: src/lib/geometry/__tests__/regionDelete.test.ts exercises the delete path — erasing a region removes only the region and leaves every boundary segment, every point and any other region untouched.",
      notes: "UNKNOWN — REQUIRES HUMAN CONFIRMATION: delete behaviour was not exercised in this pass.",
    },
  ],
};

export const geometryProperties: RequirementDomain = {
  key: "GPROP",
  title: "Geometry Properties & Relationships",
  summary:
    "Teacher-authored properties bound to geometry identity, the solution-derived Geometry Map, and the Smartboard property test.",
  coverage:
    "Built from src/lib/geometry/pickBus.ts, src/lib/smartboard/reviewProperties.tsx, ReviewPropertiesPanel.tsx, BoardRelationshipView.tsx and mem://features/geometry-map.",
  requirements: [
    {
      id: "GPROP-001",
      name: "Properties bind to the geometry object, not the label text",
      category: "Geometry properties",
      source: "Approved: 'The property is linked to the geometry object/part, not merely to the text label.'",
      requirement:
        "Each property references a stable GeoId (including sub-segment ids). Renaming or moving a label never breaks the link.",
      behaviour: ["Highlighting a property highlights the exact geometry part", "Ids survive save/reload"],
      implementation: { files: ["src/lib/geometry/pickBus.ts", "src/lib/smartboard/reviewProperties.tsx"], symbols: ["GeoId", "pickBus"] },
      dependencies: ["GEO-001"],
      validation: [{ kind: "module", target: "src/lib/geometry/pickBus.ts" }],
      restorationSource: "pickBus.ts identity-based picking (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "GPROP-002",
      name: "Built on the existing 2D editor",
      category: "Geometry properties",
      source: "Approved: 'Geometry Properties should not be another separate drawing system; build it directly on top of the existing Geometry 2D editor.'",
      requirement: "Property authoring reuses the 2D editor and its scene; no second drawing surface exists.",
      behaviour: ["Same tools, same scene, extra authoring layer only"],
      implementation: { files: ["src/components/lessonnotes/geometry-editor", "src/components/smartboard/BoardRelationshipView.tsx"] },
      dependencies: ["GEO-001"],
      validation: [{ kind: "manual", target: "Confirm no separate geometry canvas exists for properties" }],
      restorationSource: "current editor reuse",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "GPROP-003",
      name: "Geometry Map is derived from the solution",
      category: "Geometry properties",
      source: "mem://index.md Core rule + mem://features/geometry-map",
      requirement:
        "The Geometry Map is Question → Solution → Map, stored on scene.meta.geometryMap. It is never an independent theorem generator and never shows measured values.",
      behaviour: ["No numbers displayed on the map", "Map entries link by id to geometry parts", "Retired Specific/General layer must not return"],
      implementation: { files: ["src/lib/geometry/scene.ts"], symbols: ["scene.meta.geometryMap"] },
      dependencies: ["GPROP-001"],
      validation: [{ kind: "manual", target: "Open a Geometry Map and confirm no measured values are shown" }],
      restorationSource: "mem://features/geometry-map (authoritative rule)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "GPROP-004",
      name: "Properties icon opens the full-screen Relationship Page",
      category: "Geometry properties",
      source: "Approved: 'Add a properties icon near diagrams that have them, which opens a full-screen Relationship Page on the smartboard.'",
      requirement: "A diagram with authored properties shows an icon; activating it opens the full-screen relationship view on the smartboard.",
      behaviour: ["Icon appears only when properties exist", "Full-screen page shows the diagram plus its property list"],
      implementation: { files: ["src/components/smartboard/PresentationView.tsx", "src/components/smartboard/BoardRelationshipView.tsx", "src/components/smartboard/ReviewPropertiesPanel.tsx"] },
      dependencies: ["SB-005"],
      validation: [{ kind: "behaviour", target: "Open a diagram with properties on the smartboard and use the properties icon" }],
      restorationSource: "BoardRelationshipView (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "GPROP-005",
      name: "Teacher-only property test",
      category: "Geometry properties",
      source: "Approved: 'TEACHER SMARTBOARD GEOMETRY PROPERTY TEST: student mode should be removed completely.'",
      requirement: "The geometry property test is teacher-only. No student mode exists for it.",
      behaviour: ["No student entry point", "Coloured math text links answers to geometry parts"],
      implementation: { files: ["src/components/smartboard/ReviewPropertiesPanel.tsx"], symbols: ["ColoredMathText"] },
      dependencies: ["GPROP-001"],
      validation: [{ kind: "manual", target: "Confirm no student route reaches the property test" }],
      restorationSource: "student-mode removal change (current)",
      status: "PASS",
      permanent: "PENDING",
    },
  ],
};

export const geometry3d: RequirementDomain = {
  key: "G3D",
  title: "3D Geometry",
  summary: "The 3D diagram workspace, teaching controls and labelling rules.",
  coverage: "Built from the 3D geometry components, src/components/GlbViewer.tsx and the archived math122 port plan.",
  requirements: [
    {
      id: "G3D-001",
      name: "3D workspace exists alongside 2D",
      category: "Geometry 3D",
      source: "Archived plan: 'bring the 3D diagram workspace over from math122'",
      requirement: "A 3D diagram workspace is available from the diagram menu (2D/3D) and produces lesson objects like 2D does.",
      behaviour: ["Chosen from one Diagram menu", "3D object persists as note content"],
      implementation: { files: ["src/components/lessonnotes/geometry3d", "src/components/GlbViewer.tsx"] },
      dependencies: ["DIAG-001"],
      validation: [{ kind: "manual", target: "Insert a 3D diagram from the Diagram menu" }],
      restorationSource: ".lovable/plan-bring-the-3d-diagram-workspace-over-from-math122-2026-07-31.md",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "G3D-002",
      name: "Wireframe/Solid and Teach controls",
      category: "Geometry 3D",
      source: "Approved: 'Wireframe | Solid. Add Teach mode: Faces, Edges, Vertices, Open Face, Close Face, Reset.'",
      requirement:
        "3D display offers Wireframe and Solid, and a Teach mode with Faces, Edges, Vertices, Open Face, Close Face and Reset.",
      behaviour: ["Open Face unfolds a face for teaching", "Reset returns the solid to its original state"],
      implementation: { files: ["src/components/lessonnotes/geometry3d"] },
      validation: [{ kind: "behaviour", target: "Open a face, then Reset, and confirm the solid restores" }],
      restorationSource: "current Teach controls",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "G3D-003",
      name: "Radius/diameter labels measured from the centre",
      category: "Geometry 3D",
      source: "Approved: '3D Labels: Radius/Diameter from center'",
      requirement: "Radius and diameter labels originate at the centre of the solid, not at an arbitrary surface point.",
      behaviour: ["Label line starts at the centre"],
      implementation: { files: ["src/components/lessonnotes/geometry3d"] },
      validation: [{ kind: "manual", target: "Label a sphere radius and confirm the origin is the centre" }],
      restorationSource: "current 3D labelling",
      status: "PASS",
      permanent: "PENDING",
    },
  ],
};

export const diagrams: RequirementDomain = {
  key: "DIAG",
  title: "Diagram Lifecycle Across Surfaces",
  summary:
    "Diagrams as permanent lesson-note objects: section ownership, ordering, persistence, zoom, capture and the floating-page exclusion rule.",
  coverage:
    "Built from src/components/lessonnotes/GeometryDiagram.tsx, DocumentEditor.tsx, src/lib/smartboard/boardDiagrams.ts, presentation.ts, and the archived plan 'revert diagrams to Board A'.",
  requirements: [
    {
      id: "DIAG-001",
      name: "Diagrams are permanent lesson-note objects",
      category: "Diagrams",
      source: "Approved: 'Diagrams must be permanent lesson-note objects' (three layers: solution, notes, presentation)",
      requirement:
        "A diagram belongs to the lesson note and is stored with it. The database is the primary source; the editor never clears a diagram it has not loaded.",
      behaviour: [
        "Diagrams survive sign-out and sign-in.",
        "allowClear guards prevent wiping unloaded content.",
        "Pending changes are flushed on beforeunload.",
      ],
      implementation: {
        files: ["src/components/lessonnotes/DocumentEditor.tsx", "src/components/lessonnotes/GeometryDiagram.tsx"],
        symbols: ["allowClear", "syncPageGeometryNode"],
        tables: ["notebook_blocks"],
      },
      dependencies: ["LN-001", "GEO-001"],
      validation: [
        { kind: "behaviour", target: "Create a diagram, sign out, sign back in: the diagram must still be there" },
      ],
      restorationSource: "database-primary diagram loading in DocumentEditor (current)",
      status: "PASS",
      permanent: "PENDING",
      severity: "CRITICAL",
    },
    {
      id: "DIAG-002",
      name: "Section ownership and deterministic order",
      category: "Diagrams",
      source: "Approved: 'Diagrams belong to sections… must be correctly positioned and follow the right order'",
      requirement:
        "Every diagram carries its sectionKey and sectionOrdinal, so it renders in the right section and the right position on every surface.",
      behaviour: ["Order is derived from stored ordinals, not from render order", "A diagram never migrates between sections"],
      implementation: { files: ["src/lib/smartboard/presentation.ts", "src/components/lessonnotes/GeometryDiagram.tsx"], symbols: ["sectionKey", "sectionOrdinal"] },
      dependencies: ["LN-008"],
      validation: [{ kind: "module", target: "src/lib/smartboard/presentation.ts", expects: ["sectionId", "sectionLabel"] }],
      restorationSource: "sectionKey/sectionOrdinal implementation (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "DIAG-003",
      name: "One zoom control, proportional scaling",
      category: "Diagrams",
      source: "Archived plan: 'one zoom control on every page that shows a diagram' + 'Zoom must scale diagrams proportionally'",
      requirement: "Every page showing a diagram uses the same zoom control, and zoom scales the whole diagram proportionally.",
      behaviour: ["Labels, strokes and regions scale together", "No per-page bespoke zoom implementation"],
      implementation: { files: ["src/components/lessonnotes/GeometryDiagram.tsx"] },
      dependencies: ["GEO-009"],
      validation: [{ kind: "manual", target: "Zoom on note, board and relationship page and compare behaviour" }],
      restorationSource: ".lovable/drafts/.../one-zoom-control-on-every-page-that-shows-a-diagram-2026-08-24",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "DIAG-004",
      name: "Diagrams appear on Board A, inline in their section",
      category: "Diagrams",
      source:
        "Approved revert: 'The diagrams should show on Board A' — archived plan 'Revert diagrams to Board A, and remove diagrams from the Floating Numbers page' (2026-08-24)",
      requirement:
        "Each beat renders its own diagrams, tables and graphs inline on Board A, in its section and original lesson-note order, with board zoom applied.",
      behaviour: ["Board A owns lesson objects", "Board B never mirrors the section's diagrams"],
      implementation: { files: ["src/components/smartboard/PresentationView.tsx"], symbols: ["BeatBlock"] },
      dependencies: ["SB-001", "SB-006"],
      validation: [{ kind: "behaviour", target: "Open a session with a diagram on the smartboard; the diagram must render inline on Board A" }],
      restorationSource: ".lovable/plan/revert-diagrams-to-board-a-and-remove-diagrams-from-the-floa-2026-08-24.md",
      status: "PASS",
      permanent: "PENDING",
      severity: "HIGH",
    },
    {
      id: "DIAG-005",
      name: "Diagrams never enter the Floating Numbers page",
      category: "Diagrams",
      source: "Approved in the same revert: 'Diagrams should not go through floating numbers anymore.'",
      requirement:
        "The floating-number workflow contains only floating-number lines and their text/table note content. Diagram-family objects are filtered out of leading and per-line note objects.",
      behaviour: ["No diagram card can render on the floating page", "Tables are kept; diagrams are not"],
      implementation: { files: ["src/pages/FloatingNumbersPage.tsx"], symbols: ["leadingNoteObjects", "noteObjects"] },
      dependencies: ["FLT-002", "TBL-001"],
      validation: [{ kind: "behaviour", target: "Open a solution containing a diagram in floating: no diagram may appear" }],
      restorationSource: ".lovable/plan/revert-diagrams-to-board-a-and-remove-diagrams-from-the-floa-2026-08-24.md",
      status: "PASS",
      permanent: "PENDING",
      notes:
        "History note: earlier requirements carried diagrams into the floating page. That behaviour was explicitly revoked and must not be reintroduced.",
    },
    {
      id: "DIAG-006",
      name: "Only one diagram per question — no second generated diagram",
      category: "Diagrams",
      source: "Approved: 'remove the prompt/code that causes a SECOND diagram to be generated' above the Solution",
      requirement: "AI generation must not add a question-side diagram in addition to the authored one.",
      behaviour: ["No automatic diagram pass runs before the solution"],
      implementation: { files: ["src/components/lessonnotes/DocumentEditor.tsx"] },
      dependencies: ["AI-004"],
      validation: [{ kind: "behaviour", target: "Generate a solution and confirm exactly one diagram exists" }],
      restorationSource: "removal of the question-side diagram pass (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "DIAG-007",
      name: "Capture, screenshot and media import render correctly",
      category: "Diagrams",
      source: "Approved: 'COMPLETE SLIDE CAPTURE, SCREENSHOT, IMAGE & VIDEO IMPORT' + 'FIX SCREENSHOT/CAPTURE RENDERING'",
      requirement: "Capturing a diagram or board region produces a faithful image; imported images and video render at full quality.",
      behaviour: ["Captured math and diagrams are not blank or clipped", "Imported media keeps its aspect ratio"],
      implementation: { files: ["src/lib/slides", "src/components/lessonnotes/SlidePanel.tsx"] },
      dependencies: ["SLD-002"],
      validation: [{ kind: "behaviour", target: "Capture a diagram into a slide and inspect the result" }],
      restorationSource: "capture rendering fix (current)",
      status: "PASS",
      permanent: "PENDING",
    },
  ],
};
