import type { RequirementDomain } from "../types";

export const authentication: RequirementDomain = {
  key: "AUTH",
  title: "Authentication",
  summary: "Sign-up, sign-in, per-role auth pages, invitations, password reset and session lifetime.",
  coverage:
    "Built from src/routes/auth/*, src/routes/login, src/routes/signup, src/lib/auth/*, src/pages/auth/* and the auth-related memory file. Email deliverability and OAuth provider configuration are not verified at runtime here.",
  requirements: [
    {
      id: "AUTH-001",
      name: "Per-role auth pages behind one Account menu",
      category: "Authentication",
      source: "mem://features/authentication — single Account menu, per-role auth pages",
      requirement:
        "Sign-in/sign-up is entered from one Account control, with a dedicated page per role (teacher, school, parent, student, admin).",
      behaviour: [
        "Each role page collects only what that role needs.",
        "The chosen role is passed to account creation, never guessed later.",
      ],
      implementation: {
        files: [
          "src/routes/auth/index.tsx",
          "src/routes/auth/teacher.tsx",
          "src/routes/auth/school.tsx",
          "src/routes/auth/parent.tsx",
          "src/routes/auth/student.tsx",
          "src/routes/auth/admin.tsx",
          "src/pages/auth/AccountChooser.tsx",
        ],
        routes: ["/auth", "/auth/teacher", "/auth/school", "/auth/parent", "/auth/student", "/auth/admin"],
      },
      dependencies: ["ACCT-001"],
      validation: [
        { kind: "route", target: "/auth" },
        { kind: "route", target: "/auth/teacher" },
        { kind: "route", target: "/auth/student" },
      ],
      restorationSource: "current route files + mem://features/authentication",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "AUTH-002",
      name: "No anonymous sign-ups, no silent auto-confirm",
      category: "Authentication",
      source: "Platform backend rule (Cloud policy) — approved by omission of any request to change it",
      requirement: "Anonymous sign-in is disabled; email confirmation is not auto-confirmed unless explicitly requested.",
      behaviour: ["Accounts are always tied to an identity", "Verification page exists for confirmed links"],
      implementation: {
        files: ["src/routes/auth/verified.tsx", "src/pages/auth/VerifiedPage.tsx", "supabase/config.toml"],
        routes: ["/auth/verified"],
      },
      validation: [{ kind: "manual", target: "Confirm anonymous sign-in stays disabled and email confirmation is not auto-confirmed in auth settings" }],
      restorationSource: "NONE — provider configuration, not code",
      status: "PASS",
      severity: "MEDIUM",
      permanent: "PENDING",
      notes:
        "Confirmed on 2026-08-25 against the live auth settings on the Administrator's instruction: anonymous sign-in disabled, email auto-confirm off (confirmation links required), sign-up open, leaked-password protection on. Provider configuration, so this stays a manual check to repeat if the settings are ever changed.",
    },
    {
      id: "AUTH-003",
      name: "Password reset",
      category: "Authentication",
      source: "code-evidenced",
      requirement: "A signed-out person can request a reset link and set a new password.",
      behaviour: ["Reset page accepts the recovery link", "New password signs the person straight in"],
      implementation: {
        files: ["src/routes/auth/reset-password.tsx", "src/pages/auth/ResetPasswordPage.tsx"],
        routes: ["/auth/reset-password"],
      },
      validation: [{ kind: "route", target: "/auth/reset-password" }],
      restorationSource: "src/pages/auth/ResetPasswordPage.tsx",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "AUTH-004",
      name: "Protected areas never bounce a restoring session",
      category: "Authentication",
      source:
        "Approved during the 'diagrams disappear after logout/login' investigation — auth redirect loops were removed.",
      requirement:
        "Guards wait for AuthProvider.ready before redirecting; a signed-in person is never sent to /auth mid-restore.",
      behaviour: ["No redirect loop between a protected page and /auth", "Deep links survive a page refresh"],
      implementation: { files: ["src/lib/auth/AuthProvider.tsx", "src/lib/accounts/useAccount.ts"], symbols: ["ready"] },
      dependencies: ["PLAT-003"],
      validation: [
        { kind: "behaviour", target: "Refresh a protected page while signed in; it must stay on the page" },
      ],
      restorationSource: "src/lib/auth/AuthProvider.tsx (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "AUTH-005",
      name: "Invitation acceptance",
      category: "Authentication",
      source: "Approved with school invitations / teacher management",
      requirement: "An invited teacher/student can accept an invitation and land in the inviting workspace.",
      behaviour: ["Invite link resolves to the invitation", "Accepting creates or links the account and the membership"],
      implementation: {
        files: ["src/routes/auth/accept-invite.tsx", "src/pages/auth/AcceptInvitePage.tsx"],
        routes: ["/auth/accept-invite"],
        tables: ["teacher_invitations", "class_invitations", "account_memberships"],
        dbFunctions: ["accept_class_invitation", "invite_teacher_by_user", "join_org_with_invite"],
      },
      dependencies: ["WS-004", "CLS-003"],
      validation: [{ kind: "route", target: "/auth/accept-invite" }, { kind: "database", target: "teacher_invitations" }],
      restorationSource: "current page + database functions",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "AUTH-006",
      name: "Google sign-in offered",
      category: "Authentication",
      source: "Platform default (Google auth added by default and configured in the same change)",
      requirement: "Google is available as a sign-in provider and configured so first use does not error.",
      behaviour: ["OAuth redirect_uri is a same-origin public URL", "Intended destination is stored separately and applied after the session hydrates"],
      implementation: { files: ["src/pages/auth/AccountChooser.tsx"], other: ["Auth provider configuration"] },
      validation: [{ kind: "manual", target: "Sign in with Google once and confirm no 'Unsupported provider' error" }],
      restorationSource: "NONE — provider configuration",
      status: "PASS",
      severity: "MEDIUM",
      permanent: "PENDING",
      notes:
        "Confirmed on 2026-08-25: a live signed-in session on this project reports provider \"google\" with a verified Google identity, so the provider is enabled and a real Google sign-in has completed without an 'Unsupported provider' error. Provider configuration, so this stays a manual check.",
    },
  ],
};

export const accounts: RequirementDomain = {
  key: "ACCT",
  title: "Accounts, Roles & Permissions",
  summary: "Five roles, the capability engine, account ids, role dispatch and the platform owner.",
  coverage:
    "Built from src/lib/accounts/*, mem://features/account-roles, mem://features/account-architecture, mem://features/platform-console and the user_roles / role_capabilities tables.",
  requirements: [
    {
      id: "ACCT-001",
      name: "Roles live in a separate table",
      category: "Accounts",
      source: "Security standard + code-evidenced (public.user_roles, app_role enum)",
      requirement:
        "A role is stored only in public.user_roles and read through security-definer functions. Roles are never stored on profiles.",
      behaviour: [
        "app_role enum: platform_owner, co_admin, school, teacher, parent, student.",
        "has_role() / has_capability() are the only role checks used in policies.",
        "The client never proposes a role; loadAccount reads the stored role.",
      ],
      data: ["user_roles(user_id, role) unique", "role_capabilities(role, capability)"],
      permissions: ["authenticated may select own roles", "service_role full"],
      implementation: {
        files: ["src/lib/accounts/useAccount.ts", "src/lib/accounts/roles.ts"],
        symbols: ["loadAccount", "useAccount", "Capability"],
        tables: ["user_roles", "role_capabilities"],
        dbFunctions: ["has_role", "has_capability", "ensure_account", "account_role_of", "current_role_name"],
      },
      dependencies: ["AUTH-001"],
      validation: [
        { kind: "database", target: "user_roles", expects: ["user_id", "role"] },
        { kind: "database", target: "role_capabilities" },
        { kind: "module", target: "src/lib/accounts/useAccount.ts", expects: ["loadAccount", "useAccount"] },
      ],
      restorationSource: "src/lib/accounts/useAccount.ts (current, documents the rule in comments)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "ACCT-002",
      name: "Capability permission engine",
      category: "Accounts",
      source: "mem://features/account-roles — capability permission engine",
      requirement: "Features gate on capabilities, not on hard-coded role comparisons in components.",
      behaviour: ["useAccount().can(capability) is the client gate", "Server/DB enforcement mirrors the client gate"],
      implementation: {
        files: ["src/lib/accounts/useAccount.ts", "src/lib/accounts/roles.ts"],
        symbols: ["can", "capabilities"],
        tables: ["role_capabilities"],
        dbFunctions: ["has_capability"],
      },
      validation: [{ kind: "module", target: "src/lib/accounts/roles.ts", expects: ["Capability"] }],
      restorationSource: "src/lib/accounts/* (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "ACCT-003",
      name: "Role dispatcher at /home",
      category: "Accounts",
      source: "mem://features/account-roles — '/home role dispatcher'",
      requirement: "/home sends each role to its own workspace entry; '/' always stays the building.",
      behaviour: ["Teacher → teaching hub", "School → school console", "Student → student hub", "Parent → family hub", "Owner → platform console"],
      implementation: {
        files: ["src/routes/home/index.tsx", "src/pages/accounts/HomeDispatcher.tsx", "src/lib/accounts/roles.ts"],
        symbols: ["WORKSPACE_PATH"],
        routes: ["/home"],
      },
      dependencies: ["PLAT-002"],
      validation: [{ kind: "route", target: "/home" }, { kind: "module", target: "src/lib/accounts/roles.ts", expects: ["WORKSPACE_PATH"] }],
      restorationSource: "src/pages/accounts/HomeDispatcher.tsx",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "ACCT-004",
      name: "MathGPL account ids",
      category: "Accounts",
      source: "Approved with the Platform Admin console (owner account ADM/000001)",
      requirement: "Every account receives a human-readable MathGPL id; the owner is ADM/000001 and ids are immutable.",
      behaviour: ["Id issued at account creation", "Id cannot be edited afterwards"],
      data: ["account_ids table with an immutability trigger"],
      implementation: {
        tables: ["account_ids"],
        dbFunctions: ["generate_mathgpl_id", "issue_account_id", "issue_account_id_for_email", "account_ids_immutable", "mathgpl_id_for_email"],
      },
      validation: [{ kind: "database", target: "account_ids" }],
      restorationSource: "database functions (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "ACCT-005",
      name: "Platform owner privileges",
      category: "Accounts",
      source: "mem://features/platform-console — owner console + Enter Workspace impersonation",
      requirement:
        "The platform owner keeps owner powers whatever role they are viewing as, may enter a workspace read-only, and every entry is logged.",
      behaviour: ["isPlatformOwner is derived from all granted roles", "Impersonation writes an audit row", "Owner/admin accounts are not blocked by credit barriers"],
      permissions: ["guard_admin_role_changes prevents privilege escalation"],
      implementation: {
        files: ["src/lib/accounts/useAccount.ts", "src/routes/admin/route.tsx"],
        symbols: ["isPlatformOwner"],
        tables: ["admin_impersonation_log", "platform_test_accounts"],
        dbFunctions: ["enter_workspace", "has_free_access", "guard_admin_role_changes"],
      },
      dependencies: ["ADM-001", "PAY-006"],
      validation: [
        { kind: "database", target: "admin_impersonation_log" },
        { kind: "database", target: "has_free_access" },
      ],
      restorationSource: "public.has_free_access + enter_workspace (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "ACCT-006",
      name: "Parent–child and parent–teacher connections",
      category: "Accounts",
      source: "Approved in 'Parent Hub: Connect to child' and account connection rules",
      requirement: "A parent connects to a child and to that child's teachers, and sees the child's work read-only.",
      behaviour: ["Connection requires the other side to exist", "Parent view never authors on behalf of the child"],
      implementation: {
        files: ["src/routes/family/**", "src/components/family"],
        routes: ["/family", "/family/children/$childId", "/family/teachers"],
        tables: ["parent_children", "parent_teacher_links", "connections"],
        dbFunctions: ["is_connected", "my_connections", "my_connection_counts"],
      },
      dependencies: ["WS-001"],
      validation: [{ kind: "route", target: "/family" }, { kind: "database", target: "parent_children" }],
      restorationSource: "current family routes + tables",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "ACCT-007",
      name: "Student simplicity rule",
      category: "Accounts",
      source: "mem://features/platform-console — student-simplicity rules",
      requirement: "Student surfaces stay read-only hubs: no authoring tools, no admin language, no pricing internals.",
      behaviour: ["Student pages aggregate progress and open assigned work only"],
      implementation: { files: ["src/routes/student/**", "src/pages/student"], routes: ["/student"] },
      dependencies: ["RPT-002"],
      validation: [{ kind: "manual", target: "Review student routes for authoring controls that should not be there" }],
      restorationSource: "NONE — cross-cutting rule",
      status: "PASS",
      severity: "LOW",
      permanent: "PENDING",
      notes:
        "Reviewed 2026-08-25 across every /student route and src/pages/student/* screen: the surfaces open assigned work (assignments, adventures, classes, skill builder, gallery, smartboard, reports) and carry no authoring, publishing, deletion or admin controls, and no cost, margin or multiplier figures. The only prices shown are the workspace owner's published plans on the entry gateway, which are customer-facing by design.
    },
  ],
};

export const workspaces: RequirementDomain = {
  key: "WS",
  title: "Workspaces & Tenancy",
  summary: "One identity, many workspaces; strict data isolation by org_id; join codes and school invitations.",
  coverage:
    "Built from src/lib/accounts/workspace.ts, useWorkspace.ts, workspaceScope.ts, mem://features/workspace-ecosystem and the archived 'strict workspace isolation' plan.",
  requirements: [
    {
      id: "WS-001",
      name: "One identity, many workspaces",
      category: "Workspaces",
      source: "mem://index.md Core rule + mem://features/workspace-ecosystem",
      requirement:
        "profiles.active_org_id drives navigation, rosters, building and Community listing. Switching context never moves data.",
      behaviour: [
        "Every scoped query filters by the active workspace.",
        "Switching workspace invalidates cached queries and returns to '/'.",
        "Visiting another workspace is view-only unless the person owns it.",
      ],
      data: ["profiles.active_org_id", "organizations", "account_memberships"],
      implementation: {
        files: [
          "src/lib/accounts/useWorkspace.ts",
          "src/lib/accounts/workspace.ts",
          "src/lib/accounts/workspaceScope.ts",
        ],
        symbols: ["useWorkspace", "fetchWorkspaces", "setActiveWorkspace", "clearWorkspaceScopeCache", "viewOnly"],
        tables: ["profiles", "organizations", "account_memberships"],
        dbFunctions: ["current_org_id", "my_workspaces", "org_of", "is_workspace_member", "can_view_workspace", "is_org_owner"],
      },
      dependencies: ["PLAT-002", "ACCT-001"],
      validation: [
        { kind: "module", target: "src/lib/accounts/useWorkspace.ts", expects: ["useWorkspace"] },
        { kind: "database", target: "organizations" },
      ],
      restorationSource:
        ".lovable/drafts/.../strict-workspace-isolation-close-the-shelf-leak-then-audit-e-2026-08-23 (archived plan) + current code",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "WS-002",
      name: "Switching workspace opens its building",
      category: "Workspaces",
      source: "Comment-recorded decision in useWorkspace.switchTo: 'entering a workspace always opens its building first'",
      requirement: "Entering a workspace navigates to '/', never to a dashboard inside it.",
      behaviour: ["switchTo persists the active org, clears scope cache, invalidates queries, then navigates to '/'"],
      implementation: { files: ["src/lib/accounts/useWorkspace.ts"], symbols: ["switchTo"] },
      dependencies: ["RB-001"],
      validation: [{ kind: "behaviour", target: "Switch workspace and confirm the landing page is '/'" }],
      restorationSource: "src/lib/accounts/useWorkspace.ts (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "WS-003",
      name: "Strict data isolation",
      category: "Workspaces",
      source: "Approved in 'STRICT WORKSPACE ISOLATION — close the shelf leak, then audit everything'",
      requirement: "No list, shelf or picker may show content from another workspace.",
      behaviour: ["Every content query is workspace-scoped at the database level, not only in the UI"],
      permissions: ["RLS on every content table scoping to the owning organization or class"],
      implementation: {
        files: ["src/lib/accounts/workspaceScope.ts"],
        tables: ["notebooks", "classes", "gpl_assets", "adventure_games", "courses"],
        dbFunctions: ["current_org_id", "is_workspace_member"],
      },
      dependencies: ["WS-001", "AST-002"],
      validation: [
        { kind: "test", target: "src/lib/accounts/__tests__/workspaceIsolation.test.ts" },
        { kind: "manual", target: "Sign in as two workspaces and confirm no cross-listing" },
      ],
      restorationSource: "archived plan '02-leak.html / 03-fix.md' in .lovable/drafts (isolation fix)",
      status: "PASS",
      severity: "HIGH",
      permanent: "PENDING",
      notes:
        "Cleared 2026-08-25: src/lib/accounts/__tests__/workspaceIsolation.test.ts now pins the scoping contract — a school workspace filters on org_id, the personal workspace filters org_id IS NULL (never unfiltered, which was the original leak), exactly one workspace filter is applied, and view-as pins the owner filter to the viewed person.
    },
    {
      id: "WS-004",
      name: "Relationship-based join codes",
      category: "Workspaces",
      source: "mem://features/workspace-ecosystem — relationship-based join codes",
      requirement:
        "Join codes are scoped to a relationship (school↔teacher, teacher↔student, class membership) and gate what the joiner may see.",
      behaviour: ["Codes resolve to exactly one class/workspace", "Joining creates the membership row, not a data copy"],
      implementation: {
        routes: ["/join", "/join/$code", "/class/$code", "/requests"],
        tables: ["class_join_codes", "class_join_requests", "class_members", "connections"],
        dbFunctions: ["join_class_with_code", "lookup_class_by_code", "get_class_join_code", "class_join_gate", "join_org_with_invite", "generate_org_invite_code"],
      },
      dependencies: ["CLS-003"],
      validation: [{ kind: "route", target: "/join" }, { kind: "database", target: "class_join_codes" }],
      restorationSource: "current database functions",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "WS-005",
      name: "School console is read-only over teacher workspaces",
      category: "Workspaces",
      source: "Approved in 'School Console: Read-only view of teacher workspaces'",
      requirement: "A school may view its teachers' work but never author inside it.",
      behaviour: ["Viewing frame marks the context as view-only", "No save/publish controls in school view"],
      implementation: {
        files: ["src/components/school/ViewingFrame.tsx", "src/pages/school/SchoolPeoplePage.tsx"],
        routes: ["/school", "/school/teachers", "/school/teachers/$userId/lesson-notes/$id"],
        symbols: ["ViewingFrame", "viewOnly"],
      },
      dependencies: ["WS-001"],
      validation: [
        { kind: "route", target: "/school/teachers" },
        { kind: "module", target: "src/components/school/ViewingFrame.tsx" },
      ],
      restorationSource: "src/components/school/ViewingFrame.tsx (current; hook-order fix applied 2026-08)",
      status: "PASS",
      permanent: "PENDING",
    },
  ],
};
