import type { RequirementDomain } from "../types";

export const lessonNotes: RequirementDomain = {
  key: "LN",
  title: "Lesson Notes (Notebook)",
  summary:
    "The continuous editable document: section hierarchy, sessions, auto-numbering, persistence, archive/dustbin, lesson modes and note storage.",
  coverage:
    "Built from src/components/lessonnotes/*, src/lib/lessonnotes/*, src/hooks/useNotebook.ts, notebooks / notebook_sections / notebook_subsections / notebook_blocks and mem://features/lesson-note-storage.",
  requirements: [
    {
      id: "LN-001",
      name: "Fixed section hierarchy",
      category: "Lesson notes",
      source:
        "Approved: 'Redesign Note hierarchy: Introduction, Explanation, Example, Exercise, Classwork, Homework, Summary'",
      requirement:
        "A lesson note is built from exactly these section kinds: introduction, explanation, example, exercise, classwork, homework, summary. 'Advanced' was removed and must not return.",
      behaviour: [
        "section_kind enum matches the approved list.",
        "Sections can be inserted at the cursor position.",
        "No 'Advanced' section type anywhere in the UI.",
      ],
      data: ["section_kind enum: introduction, explanation, example, exercise, classwork, homework, summary"],
      implementation: {
        files: ["src/components/lessonnotes/DocumentEditor.tsx", "src/lib/lessonnotes/sessionLayout.ts", "src/hooks/useNotebook.ts"],
        tables: ["notebook_sections", "notebook_subsections", "notebook_blocks"],
      },
      validation: [{ kind: "database", target: "section_kind" }, { kind: "module", target: "src/hooks/useNotebook.ts" }],
      restorationSource: "section_kind enum (current) — authoritative",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "LN-002",
      name: "Continuous editable workspace",
      category: "Lesson notes",
      source: "Approved: 'Continuous editable workspace' + Master Sensor rebuild",
      requirement:
        "The note is one continuous document, not a stack of isolated boxes. A persistent Master Sensor (caret) handles backspace, typing and editing across section boundaries.",
      behaviour: [
        "Typing never loses the caret when crossing a heading.",
        "Backspace at a boundary merges the way a document does.",
        "Switching sections never resets, pauses or locks the workspace.",
      ],
      implementation: {
        files: ["src/components/lessonnotes/DocumentEditor.tsx", "src/components/lessonnotes/SensorCaret.tsx", "src/lib/lessonnotes/sessionLayout.ts"],
        symbols: ["SensorCaret"],
      },
      dependencies: ["STAB-002"],
      validation: [
        { kind: "behaviour", target: "Type across a section boundary; caret and content must survive" },
        { kind: "manual", target: "Switch sections repeatedly and confirm no freeze" },
      ],
      restorationSource: "src/components/lessonnotes/DocumentEditor.tsx (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "LN-003",
      name: "Draggable dustbin and archive library",
      category: "Lesson notes",
      source: "Approved: 'Remove Advanced, add draggable Dustbin. Archive to dedicated library.'",
      requirement: "Content is deleted by dragging to a movable dustbin; deleted/archived content lands in a dedicated archive library, not oblivion.",
      behaviour: ["Dustbin position is user-movable", "Archive is browsable and restorable"],
      implementation: {
        files: ["src/hooks/useDraggableTab.ts", "src/pages/TeachingHubArchive.tsx", "src/hooks/useArchivedFeature.ts"],
        routes: ["/teaching-hub/archive"],
        tables: ["archived_features"],
      },
      validation: [{ kind: "route", target: "/teaching-hub/archive" }, { kind: "module", target: "src/hooks/useDraggableTab.ts" }],
      restorationSource: "current archive page + useDraggableTab",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "LN-004",
      name: "Three lesson modes, Manual is the default",
      category: "Lesson notes",
      source: "Approved: 'MATHSGPL — DEFAULT LESSON MODE REBUILD' (Manual default, AI Builder, Copilot)",
      requirement:
        "Manual mode is the default and the foundation. AI Builder and Copilot are opt-in. In Manual mode AI acts as an editor (formatting/LaTeX cleanup), never as the author.",
      behaviour: [
        "A new note opens in Manual mode.",
        "AI panels are non-modal sidebars and never block the document.",
        "Mode is explicit and visible.",
      ],
      implementation: {
        files: ["src/lib/lessonnotes/aiMode.ts", "src/components/lessonnotes/AiSettingsPanel.tsx", "src/lib/lessonnotes/autoNumber.ts"],
        symbols: ["aiMode"],
      },
      dependencies: ["AI-001", "AI-002"],
      validation: [{ kind: "module", target: "src/lib/lessonnotes/aiMode.ts" }],
      restorationSource: "src/lib/lessonnotes/aiMode.ts (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "LN-005",
      name: "Auto-numbering of Examples and Solutions",
      category: "Lesson notes",
      source: "Approved with the lesson mode rebuild ('auto-numbering for Examples/Solutions')",
      requirement: "Examples and their Solutions are numbered automatically and renumber when content is inserted or removed.",
      behaviour: ["Numbering is derived, never typed", "Solution inherits the number of its Example"],
      implementation: { files: ["src/lib/lessonnotes/autoNumber.ts"], symbols: ["autoNumber"] },
      validation: [{ kind: "module", target: "src/lib/lessonnotes/autoNumber.ts" }],
      restorationSource: "src/lib/lessonnotes/autoNumber.ts",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "LN-006",
      name: "Solution is an independent editable section",
      category: "Lesson notes",
      source: "Approved: 'Make Solution an independent editable section' + auto-insert Solution blocks",
      requirement:
        "A Solution is its own editable block under its question, inserted automatically for question sessions, editable like any other content.",
      behaviour: ["Solution appears directly under the session heading", "Teacher can edit it freely afterwards"],
      data: ["block_kind enum: problem, solution, reasoning, text"],
      implementation: { files: ["src/components/lessonnotes/DocumentEditor.tsx"], tables: ["notebook_blocks"] },
      dependencies: ["SB-002"],
      validation: [{ kind: "database", target: "block_kind" }],
      restorationSource: "block_kind enum + DocumentEditor (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "LN-007",
      name: "Notes are saved and sorted by recency",
      category: "Lesson notes",
      source: "Approved: 'Ensure that any lesson note I create is saved and sorted by recency'",
      requirement: "The lesson-notes list is ordered by updated_at descending.",
      behaviour: ["Most recently edited note is first"],
      implementation: { files: ["src/pages/lessonnotes/LessonNotesPage.tsx"], tables: ["notebooks"], routes: ["/lesson-notes"] },
      validation: [{ kind: "route", target: "/lesson-notes" }, { kind: "manual", target: "Confirm ordering is updated_at desc" }],
      restorationSource: "LessonNotesPage ordering (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "LN-008",
      name: "Durable session identity",
      category: "Lesson notes",
      source:
        "Approved after the floating mismatch bug ('floating was showing the solution of another problem') — sections carry a durable doc_key.",
      requirement:
        "Every session/section has a durable identity (doc_key) so downstream surfaces resolve the right question, independent of position.",
      behaviour: ["Reordering content never re-points a floating page or smartboard at a different question"],
      implementation: {
        files: ["src/lib/lessonnotes/lessonOutline.ts"],
        symbols: ["doc_key"],
        tables: ["notebook_sections"],
      },
      dependencies: ["FLT-001", "SB-001"],
      validation: [{ kind: "database", target: "notebook_sections", expects: ["doc_key"] }],
      restorationSource: "notebook_sections.doc_key migration + lessonOutline.ts",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "LN-009",
      name: "Shared-note writes are permitted for members",
      category: "Lesson notes",
      source: "Fix approved after: 'Adding sections or subsections to a notebook fails for non-owners'",
      requirement:
        "A person with legitimate access to a shared note may add sections/subsections; policy denials are surfaced clearly, not silently swallowed.",
      behaviour: ["guardWrite reports a readable reason on denial", "Owner and permitted members can both write"],
      permissions: ["notebooks / notebook_sections RLS covering owner and shared-member writes"],
      implementation: { files: ["src/hooks/useNotebook.ts"], symbols: ["guardWrite"], dbFunctions: ["notebook_shared_to_member"] },
      dependencies: ["WS-003"],
      validation: [{ kind: "module", target: "src/hooks/useNotebook.ts", expects: ["guardWrite"] }, { kind: "database", target: "notebook_shared_to_member" }],
      restorationSource: "useNotebook.guardWrite + the shared-note RLS migration",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "LN-010",
      name: "Workspace vs class note storage",
      category: "Lesson notes",
      source: "mem://features/lesson-note-storage",
      requirement:
        "A note lives in the workspace; putting it in a class duplicates it. Checkout/save-back moves work between the two without merging the copies.",
      behaviour: ["Class copy is independent of the workspace original", "Save-back is explicit"],
      implementation: { tables: ["notebooks", "class_lesson_notes", "class_content_nodes"] },
      dependencies: ["CLS-002"],
      validation: [{ kind: "database", target: "class_lesson_notes" }],
      restorationSource: "mem://features/lesson-note-storage + current tables",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "LN-011",
      name: "AI notebook cover designer",
      category: "Lesson notes",
      source: "Approved: 'AI Cover Generator (10 themes)'",
      requirement: "A note cover can be generated from a fixed set of themes and stored on the notebook.",
      behaviour: ["Ten themes offered", "Generated cover is saved to the note, not regenerated on each view"],
      implementation: { tables: ["notebooks"], other: ["cover generation function"] },
      validation: [
        { kind: "manual", target: "Generate a cover and confirm it persists" },
        { kind: "test", target: "src/lib/lessonnotes/__tests__/coverThemes.test.ts" },
      ],
      restorationSource: "src/lib/lessonnotes/coverThemes.ts + CoverDesignerDialog (current)",
      status: "PASS",
      severity: "LOW",
      permanent: "PENDING",
      notes:
        "Cleared 2026-08-25: CoverDesignerDialog is reachable from the notebook card menu and its onSave writes cover_config to the notebooks row (src/pages/LessonNotesPage.tsx saveCover), so the cover is stored, not regenerated per view. src/lib/lessonnotes/__tests__/coverThemes.test.ts pins exactly ten unique themes, one suggestion per theme and verbatim read-back of a stored cover.",
    },
    {
      id: "LN-012",
      name: "Optional curriculum hierarchy",
      category: "Lesson notes",
      source: "Archived plan: 'optional curriculum hierarchy for class lesson notes'",
      requirement: "Class lesson notes may optionally sit inside a curriculum hierarchy; the hierarchy is never mandatory.",
      behaviour: ["Notes work with no curriculum assigned"],
      implementation: { files: ["src/data/curriculum.ts"], tables: ["class_content_nodes"] },
      validation: [{ kind: "module", target: "src/data/curriculum.ts" }],
      restorationSource: ".lovable/plan-optional-curriculum-hierarchy-for-class-lesson-notes-2026-07-29.md",
      status: "PASS",
      permanent: "PENDING",
    },
  ],
};

export const mathEditing: RequirementDomain = {
  key: "MATH",
  title: "Mathematical Editing & Rendering",
  summary:
    "The math structure model, keyboard productivity, matrices, the asset library and the rule that raw syntax is never visible.",
  coverage:
    "Built from src/components/structures/*, src/lib/lessonnotes/assets/*, src/lib/smartboard/mathTree*.ts, src/lib/mathengine/* and the rendering-standard files in supabase/functions/notebook-ai.",
  requirements: [
    {
      id: "MATH-001",
      name: "Zero raw mathematical syntax is ever visible",
      category: "Math editing",
      source:
        "Approved repeatedly, most explicitly: 'ensure zero raw mathematical syntax is ever visible to the teacher'",
      requirement:
        "No surface (lesson note, smartboard, floating page, AI panel) may display LaTeX source, markdown fences or tool directives. Everything is rendered.",
      behaviour: [
        "AI output passes through hygiene before display.",
        "Matrices, summations, integrals, roots render as structures, not source.",
      ],
      implementation: {
        files: [
          "src/lib/lessonnotes/outputHygiene.ts",
          "src/lib/lessonnotes/aiToNodes.ts",
          "src/lib/lessonnotes/materializeDirectives.ts",
          "src/components/smartboard/MathTreeRender.tsx",
          "supabase/functions/notebook-ai/renderingStandard.ts",
        ],
        symbols: ["outputHygiene", "segmentMathLine", "materializeDirectives", "renderMathInline"],
      },
      dependencies: ["AI-003"],
      validation: [
        { kind: "test", target: "src/lib/lessonnotes/__tests__ (existing AI/matrix/symbol tests)" },
        { kind: "module", target: "src/lib/lessonnotes/outputHygiene.ts" },
      ],
      restorationSource: "outputHygiene.ts + renderingStandard.ts (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "MATH-002",
      name: "Editable cursor with infinite nesting",
      category: "Math editing",
      source: "Approved: 'Redesign: Editable Cursor with infinite nesting. Arrow keys move between branches; Space exits one level.'",
      requirement:
        "Math structures nest without limit. Arrow keys move between branches, Space exits one level, and empty slots show subtle placeholders while reading like natural text.",
      behaviour: ["No depth cap", "Placeholders are subtle, not intrusive", "Caret never gets trapped in a slot"],
      implementation: { files: ["src/components/structures/MathStructure.tsx", "src/lib/lessonnotes/MathKeyShortcuts.ts"], symbols: ["MathStructure"] },
      validation: [{ kind: "module", target: "src/components/structures/MathStructure.tsx" }],
      restorationSource: "src/components/structures/MathStructure.tsx (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "MATH-003",
      name: "Keyboard productivity shortcuts",
      category: "Math editing",
      source: "Approved: '@ for trigger menu, # for Superscript, ## for Subscript, / for fraction, smart brackets'",
      requirement:
        "@ opens the asset trigger menu; # gives superscript; ## gives subscript; / gives a smart fraction; brackets grow with content. These work in the note and inside table cells.",
      behaviour: ["Shortcuts work identically in lesson note text and in table cells", "Smart brackets resize with their content"],
      implementation: {
        files: ["src/lib/lessonnotes/MathKeyShortcuts.ts", "src/components/lessonnotes/MathCellEditor.tsx"],
        symbols: ["MathKeyShortcuts"],
      },
      dependencies: ["TBL-004"],
      validation: [{ kind: "module", target: "src/lib/lessonnotes/MathKeyShortcuts.ts" }, { kind: "behaviour", target: "Type # and ## inside a table cell" }],
      restorationSource: "MathKeyShortcuts.ts + MathCellEditor.tsx (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "MATH-004",
      name: "Matrix is one atomic structure",
      category: "Math editing",
      source:
        "Corrected requirement, stated explicitly: matrices must 'behave more like square root and exponent', shown compactly as 2×2/3×3 and expanded on the smartboard.",
      requirement:
        "A matrix is a single atomic structure like a root or fraction. In compact contexts it appears as its dimensions; clicking it on the smartboard opens a pre-filled editable matrix. It is never decomposed into separate floating cells.",
      behaviour: [
        "Compact chip shows the dimensions, not per-cell content.",
        "Smartboard expansion is pre-filled from the saved LaTeX.",
        "Brackets scale with rows/columns; SVG brackets, not glyph stacks.",
      ],
      implementation: {
        files: [
          "src/components/structures/MathStructure.tsx",
          "src/components/structures/MatrixCreateDialog.tsx",
          "src/pages/FloatingNumbersPage.tsx",
          "src/components/smartboard/FloatingWorkspace.tsx",
          "src/components/smartboard/FloatingNumberPanel.tsx",
          "src/components/smartboard/PresentationView.tsx",
        ],
        symbols: ["ensureAtomicMatrixFiller", "latexToTree"],
      },
      dependencies: ["FLT-004", "SB-004"],
      validation: [
        { kind: "test", target: "matrix parsing tests under src/lib/**/__tests__" },
        { kind: "behaviour", target: "Click a 2×2 chip on the smartboard and confirm a pre-filled editable matrix" },
      ],
      restorationSource: "ensureAtomicMatrixFiller + latexToTree path (current)",
      status: "PASS",
      permanent: "PENDING",
      notes:
        "History note: an earlier implementation treated matrices as interactive table branches. That reading was rejected and must not be reintroduced.",
    },
    {
      id: "MATH-005",
      name: "Asset registry with favourites and recents",
      category: "Math editing",
      source: "Approved: 'Favourites/Recents in Asset Library with ❤️' + data-driven asset registry",
      requirement:
        "Every insertable item is a declarative AssetDef; adding an asset requires no editor code change. The library offers favourites and recents.",
      behaviour: ["Short codes are unique and auto-derived when omitted", "Favourites persist per person"],
      implementation: { files: ["src/lib/lessonnotes/assets/types.ts", "src/lib/lessonnotes/assets"], symbols: ["AssetDef", "AssetRender"] },
      validation: [{ kind: "module", target: "src/lib/lessonnotes/assets/types.ts", expects: ["AssetDef"] }],
      restorationSource: "src/lib/lessonnotes/assets/types.ts (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "MATH-006",
      name: "Lossless math serialisation between surfaces",
      category: "Math editing",
      source: "Approved: 'the floating view must not reconstruct or reinterpret the solution'",
      requirement:
        "Math travels between lesson note, floating page and smartboard as the same structure — serialised losslessly, never re-parsed from display text.",
      behaviour: ["Fractions, labels, points and formatting survive the trip", "No surface re-derives math from rendered text"],
      implementation: {
        files: ["src/lib/lessonnotes/mathStructureLatex.ts", "src/lib/smartboard/mathTreeLatex.ts", "src/lib/smartboard/mathTree.ts"],
      },
      dependencies: ["FLT-002"],
      validation: [{ kind: "module", target: "src/lib/lessonnotes/mathStructureLatex.ts" }],
      restorationSource: "mathStructureLatex.ts / mathTreeLatex.ts (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "MATH-007",
      name: "Emoji library",
      category: "Math editing",
      source: "Approved: 'Emoji Library Panel (30% right dock)' + emoji integrity across surfaces",
      requirement: "Emoji are inserted from a docked library and render identically in the note, smartboard and floating surfaces.",
      behaviour: ["Right dock at ~30% width", "Categories and items are data rows, not hard-coded"],
      implementation: { files: ["src/components/smartboard/BoardEmojiDock.tsx"], tables: ["emoji_categories", "emoji_items"] },
      validation: [{ kind: "database", target: "emoji_items" }, { kind: "module", target: "src/components/smartboard/BoardEmojiDock.tsx" }],
      restorationSource: ".lovable/plan-emoji-library-for-lesson-notes-2026-07-29.md + current tables",
      status: "PASS",
      permanent: "PENDING",
    },
  ],
};

export const tables: RequirementDomain = {
  key: "TBL",
  title: "Smart Tables",
  summary: "Tables as first-class objects through the whole workflow, with calculator cells, sums and branch numbering.",
  coverage: "Built from src/components/lessonnotes/SmartTable.tsx, src/lib/floating/tableGrid.ts, src/lib/smartboard/*, TableActivityStage.tsx.",
  requirements: [
    {
      id: "TBL-001",
      name: "A table stays a table everywhere",
      category: "Tables",
      source: "Approved: 'A table must remain a table throughout the entire workflow'",
      requirement:
        "A table authored in the lesson note remains a grid in the solution, the floating pages and the smartboard. It is never flattened into text lines.",
      behaviour: ["Headers retained by default", "Grid rendering on the smartboard", "First floating line of a table solution is the table itself"],
      implementation: {
        files: ["src/components/lessonnotes/SmartTable.tsx", "src/lib/floating/tableGrid.ts", "src/components/smartboard/PresentationView.tsx", "src/lib/assessment/createAssessment.ts"],
        symbols: ["FloatingTableRef", "TableGridViewer"],
      },
      dependencies: ["FLT-002", "SB-004"],
      validation: [
        { kind: "behaviour", target: "Open a table solution on the floating page: line 1 must be the table" },
        { kind: "behaviour", target: "Open the same session on the smartboard: the grid must appear" },
      ],
      restorationSource: "FloatingTableRef + TableGridViewer path (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "TBL-002",
      name: "Tables are branch points (Tk.n)",
      category: "Tables",
      source: "Approved: 'MULTIPLE TABLES INSIDE ONE SOLUTION' — T1 → T1.1 does not renumber the main L-sequence",
      requirement:
        "The main solution flow is numbered L1..Ln. Each table opens a branch numbered Tk, whose children are Tk.1, Tk.2… Branch numbering never renumbers the main sequence.",
      behaviour: [
        "Multiple tables can coexist in one solution.",
        "Next at the end of a branch returns to the next main node.",
        "Re-opening a table restores its state.",
      ],
      implementation: {
        files: ["src/lib/smartboard/tableActivity.ts", "src/components/smartboard/PresentationView.tsx", "src/pages/FloatingNumbersPage.tsx"],
        symbols: ["tableActivity"],
      },
      dependencies: ["FLT-003"],
      validation: [
        { kind: "test", target: "src/lib/smartboard/__tests__/tableBranching.test.ts" },
        { kind: "behaviour", target: "Two tables in one solution: confirm T1.x then T2.x with the main sequence intact" },
      ],
      restorationSource: "src/lib/smartboard/tableActivity.ts (current)",
      status: "PASS",
      severity: "MEDIUM",
      permanent: "PENDING",
      notes:
        "Cleared 2026-08-25: src/lib/smartboard/__tests__/tableBranching.test.ts pins T1/T2 branch identity, Tk.1/Tk.2 children, the untouched L1/L2/L3 main sequence across two tables, return to the next main step at the end of a branch, and one branch per table even when its lines are not contiguous.",
    },
    {
      id: "TBL-003",
      name: "Per-step marking inside a table",
      category: "Tables",
      source: "Approved: 'After completing T1.1, the system should assess and mark it immediately before I move to T1.2'",
      requirement: "Each table step is assessed and marked as it is completed, not only at the final answer.",
      behaviour: ["Marks are awarded per track/step", "Moving on shows the mark for the step just finished"],
      implementation: { files: ["src/components/smartboard/PresentationView.tsx", "src/components/smartboard/TableActivityStage.tsx"] },
      dependencies: ["ASMT-003"],
      validation: [{ kind: "behaviour", target: "Complete T1.1 and confirm it is marked before T1.2 opens" }],
      restorationSource: "per-track marking in PresentationView (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "TBL-004",
      name: "Calculator cells, Sum Row and Sum Column",
      category: "Tables",
      source: "Approved: 'Calculator cells (eval on Enter). Sum Row/Column buttons.' + Σ summation plan",
      requirement:
        "A cell can evaluate an expression on Enter. Sum Row and Sum Column controls exist in the table settings and on the smartboard activity stage.",
      behaviour: ["Enter evaluates, does not just commit text", "Sum controls insert a computed total"],
      implementation: {
        files: ["src/components/lessonnotes/SmartTable.tsx", "src/components/smartboard/TableActivityStage.tsx", "src/components/lessonnotes/MathCellEditor.tsx"],
      },
      dependencies: ["MATH-003"],
      validation: [{ kind: "behaviour", target: "Type 2+3 in a calculator cell, press Enter, expect 5" }],
      restorationSource: ".lovable/plan-smart-table-cell-calculator-summation-σ-2026-07-30.md + current code",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "TBL-005",
      name: "AI fills editable cells only; eraser clears student values only",
      category: "Tables",
      source: "Approved: 'AI populates editable cells but protects static structures. Eraser clears student values only.'",
      requirement: "AI and the eraser may only touch student-editable cells; authored structure and headers are protected.",
      behaviour: ["Static cells are immutable to AI", "Eraser leaves the authored table intact"],
      implementation: { files: ["src/components/lessonnotes/SmartTable.tsx", "src/lib/lessonnotes/materializeDirectives.ts"] },
      dependencies: ["AI-002"],
      validation: [{ kind: "behaviour", target: "Run the eraser on a filled table and confirm headers/structure survive" }],
      restorationSource: "current SmartTable cell protection",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "TBL-006",
      name: "Teacher-owned cell sensor on the smartboard",
      category: "Tables",
      source: "Fix approved after: 'Smartboard table first cell focus jumps'",
      requirement:
        "On the smartboard, the table sensor is teacher-owned: typing a value never auto-advances the sensor to the next cell.",
      behaviour: ["Focus stays until the teacher moves it", "First cell does not lose focus on the first keystroke"],
      implementation: { files: ["src/components/smartboard/TableActivityStage.tsx", "src/lib/smartboard/mathTokens.ts"] },
      validation: [{ kind: "behaviour", target: "Type a digit in the first cell; focus must not jump" }],
      restorationSource: "structure-aware tokenisation in mathTokens.ts (current)",
      status: "PASS",
      permanent: "PENDING",
    },
  ],
};

export const charts: RequirementDomain = {
  key: "CHT",
  title: "Charts & Graphs",
  summary: "Bar chart, histogram, pie chart, line/trend charts and their shared geometry rules.",
  coverage: "Built from src/components/lessonnotes/charts/*, src/components/reports/*, src/lib/charts/*.",
  requirements: [
    {
      id: "CHT-001",
      name: "Bar geometry rules",
      category: "Charts",
      source:
        "Approved: 'Default width of bars 2% of the graph. Distance between bars equals the bar width. Histogram bars meshed. Y-axis to first bar equals the bar width.'",
      requirement:
        "Bar width defaults to 2% of the plot width; gap between bars equals the bar width; the offset from the Y-axis to the first bar equals the bar width; a histogram uses zero gap.",
      behaviour: ["Changing bar width moves the gaps and the first-bar offset with it", "Histogram bars touch"],
      implementation: { files: ["src/components/lessonnotes/charts/BarChart.tsx", "src/lib/charts/scale.ts", "src/lib/charts/types.ts"] },
      validation: [
        { kind: "test", target: "src/lib/__tests__/chartBarGeometry.test.ts" },
        { kind: "manual", target: "Measure gap vs bar width" },
      ],
      restorationSource: "src/components/lessonnotes/extensions/visuals/smartchart/barLayout.ts (current)",
      status: "PASS",
      severity: "LOW",
      permanent: "PENDING",
      notes:
        "Cleared 2026-08-25: the geometry arithmetic was extracted to barLayout.ts (the renderer no longer derives it inline) and src/lib/__tests__/chartBarGeometry.test.ts pins gap = bar width, Y-axis-to-first-bar = bar width, width changes moving both, and zero gap for a histogram.",
    },
    {
      id: "CHT-002",
      name: "Charts are unbounded; the notebook is the boundary",
      category: "Charts",
      source: "Approved: 'Charts shouldn't be bounded; the notebook is the boundary' + Extend control",
      requirement:
        "A chart can extend to the full notebook width and to a chosen height (starting at 20cm) via an Extend control in its settings.",
      behaviour: ["Full-width mode spans the notebook", "Height is authorable, default 20cm"],
      implementation: { files: ["src/components/lessonnotes/charts/SmartGraphView.tsx"] },
      validation: [{ kind: "module", target: "src/components/lessonnotes/charts/SmartGraphView.tsx" }],
      restorationSource: "SmartGraphView full-width mode (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "CHT-003",
      name: "Direct bar editing and axis controls",
      category: "Charts",
      source:
        "Approved: '+ on the X-axis to add bars. 1 cm = X units on the Y-axis. Hovering a bar shows +/- (plus = +1cm, minus = -0.2cm). Larger, higher-contrast scale input.'",
      requirement: "Bars are edited directly on the chart: add via the X-axis +, change height via hover +/- with those exact steps, and the Y-axis states the cm-to-units scale.",
      behaviour: ["+ adds a bar at the axis position", "Hover controls change height by +1cm / -0.2cm", "Scale input is legible (font size and contrast)"],
      implementation: { files: ["src/components/lessonnotes/charts/BarChart.tsx", "src/components/lessonnotes/charts/SmartGraphView.tsx"] },
      dependencies: ["CHT-001"],
      validation: [{ kind: "behaviour", target: "Hover a bar, press + then -, confirm 1cm and 0.2cm steps" }],
      restorationSource: "current BarChart hover controls",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "CHT-004",
      name: "Pie chart totals 100% with validation",
      category: "Charts",
      source: "Approved: 'Pie Chart: Total always 100% with validation. Labels: Category, %, or both. Full width.'",
      requirement: "A pie chart validates that its slices total 100% and offers label modes: category, percentage, or both.",
      behaviour: ["Invalid totals are reported, not silently normalised", "Three label modes available"],
      implementation: { files: ["src/components/lessonnotes/charts/PieChart.tsx"] },
      validation: [{ kind: "behaviour", target: "Enter slices totalling 90% and confirm the validation message" }],
      restorationSource: "src/components/lessonnotes/charts/PieChart.tsx (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "CHT-005",
      name: "Histogram shares bar-chart settings",
      category: "Charts",
      source: "Approved: 'Ensure Histogram uses same settings as Bar Chart'",
      requirement: "The histogram uses the bar chart's settings panel, differing only in zero bar spacing.",
      behaviour: ["No separate settings implementation for histograms"],
      implementation: { files: ["src/components/lessonnotes/charts/BarChart.tsx", "src/lib/charts/types.ts"] },
      dependencies: ["CHT-001"],
      validation: [{ kind: "manual", target: "Open histogram settings and confirm parity with bar chart" }],
      restorationSource: "shared chart settings (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "CHT-006",
      name: "Dark ink on chart text",
      category: "Charts",
      source: "Approved: 'Ensure the diagram is top-notch and all text is black' + universal legibility rule",
      requirement: "Axis labels, tick values and chart text render in dark ink with visible axes by default.",
      behaviour: ["No white-on-white or low-contrast axis text"],
      implementation: { files: ["src/components/lessonnotes/charts", "src/lib/charts"] },
      dependencies: ["DES-001"],
      validation: [{ kind: "manual", target: "Insert a chart and confirm dark, legible axis text" }],
      restorationSource: "forced dark-ink axis/labels change (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "CHT-007",
      name: "Progress and trend charts in reports",
      category: "Charts",
      source: "Approved: 'Student Progress Bar Chart (Y-axis 0-100%)' and 'Trend Chart with carry-forward, weekly grouping, infinite horizontal scroll, sticky Y-axis'",
      requirement:
        "Reports use a progress bar chart with a 0–100% Y-axis and a trend line chart with carry-forward values, weekly grouping, horizontal scrolling and a sticky Y-axis.",
      behaviour: ["Class report shows averages", "Weeks with no data carry the previous value forward"],
      implementation: { files: ["src/components/reports/ProgressBarChart.tsx", "src/components/reports/TrendLineChart.tsx"] },
      dependencies: ["RPT-001"],
      validation: [{ kind: "module", target: "src/components/reports/TrendLineChart.tsx" }],
      restorationSource: "current report chart components",
      status: "PASS",
      permanent: "PENDING",
    },
  ],
};
