import type { RequirementDomain } from "../types";

export const commerce: RequirementDomain = {
  key: "PAY",
  title: "Credits, Plans & Payments",
  summary:
    "Prepaid credits with a FIFO ledger, versioned plans, entitlements, subscriptions, payments and the gateway.",
  coverage:
    "Built from src/lib/credits/*, src/lib/plans/*, src/utils/payments.functions.ts, supabase/functions/_shared/creditGate.ts and usageMeter.ts, the credit_*/plan_*/subscription_*/gateway_* tables and mem://features/credit-economics, plan-engine, plan-entitlements, payments, credit-control, gateway-pricing, gateway-stripe-connect.",
  requirements: [
    {
      id: "PAY-001",
      name: "Every billable resource consumes credits",
      category: "Credits",
      source: "Approved: 'MASTER PROMPT — Payments, Pricing, & Credits: Every billable resource uses credits.'",
      requirement:
        "AI, storage, compute, network, database and realtime usage is metered into credits. Usage is reserved before work starts and settled after.",
      behaviour: [
        "Server-side reservation with floors (0.50 start, 0.30 stop).",
        "Idempotency keys prevent double charging.",
        "FIFO deduction across credit lots.",
      ],
      implementation: {
        files: ["supabase/functions/_shared/creditGate.ts", "supabase/functions/_shared/usageMeter.ts"],
        tables: ["credit_wallets", "credit_ledger", "credit_grants", "credit_reservations", "usage_events", "cost_units", "cost_unit_totals"],
        dbFunctions: ["consume_credits", "consume_cost_credits", "can_afford_usage", "credit_headroom", "adjust_credits", "ensure_credit_wallet", "expire_credit_grants", "apply_usage_payment"],
      },
      dependencies: ["PAY-002"],
      validation: [
        { kind: "database", target: "credit_ledger" },
        { kind: "module", target: "supabase/functions/_shared/creditGate.ts" },
      ],
      restorationSource: "mem://features/credit-control + current credit functions",
      status: "PASS",
      permanent: "PENDING",
      severity: "CRITICAL",
    },
    {
      id: "PAY-002",
      name: "Prepaid credits are locked to purchase-time pricing",
      category: "Credits",
      source: "mem://index.md Core rule + mem://features/credit-economics",
      requirement:
        "Credits are prepaid and locked to the pricing terms at purchase. Admin cost+profit are the only pricing inputs. Cost, margin and multipliers are never shown to customers.",
      behaviour: ["Immutable pricing versions", "Per-lot FIFO multipliers", "Customer view shows balance and value only"],
      implementation: {
        tables: ["pricing_versions", "credit_purchases", "credit_packages", "resource_prices", "platform_cost_settings"],
        dbFunctions: ["credit_value_at", "my_credit_balance", "my_credit_summary", "my_credit_activity"],
      },
      validation: [{ kind: "database", target: "pricing_versions" }, { kind: "manual", target: "Confirm no customer surface shows cost or margin" }],
      restorationSource: "mem://features/credit-economics (authoritative)",
      status: "PASS",
      permanent: "PENDING",
      severity: "CRITICAL",
    },
    {
      id: "PAY-003",
      name: "Subscription credits are separate from prepaid credits",
      category: "Credits",
      source: "Approved: 'Split subscription from prepaid.'",
      requirement: "Included plan credits and purchased credits are tracked separately and consumed in a defined order.",
      behaviour: ["Included credits are derived from the plan version", "Purchased lots survive a plan change"],
      implementation: { tables: ["subscriptions", "plan_versions", "credit_grants"], dbFunctions: ["activate_subscription", "downgrade_to_free_plan", "expire_lapsed_subscriptions"] },
      dependencies: ["PAY-004"],
      validation: [{ kind: "database", target: "credit_grants" }],
      restorationSource: "mem://features/plan-engine",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "PAY-004",
      name: "Versioned plans and entitlements",
      category: "Plans",
      source: "mem://features/plan-engine + mem://features/plan-entitlements",
      requirement:
        "Plans are versioned with draft→publish, subscriptions lock to a version, and features/limits are declared per plan and enforced client-side, server-side and in the database.",
      behaviour: ["Publishing a new version never changes existing subscriptions", "Limits are effective values, not hard-coded"],
      implementation: {
        routes: ["/admin/plans", "/plans"],
        tables: ["plans", "plan_versions", "plan_features", "plan_limits", "plan_entitlements", "feature_entitlements", "subscription_entitlements", "subscription_limits"],
        dbFunctions: ["account_plan_id", "account_features", "effective_entitlements", "effective_limit", "has_entitlement"],
      },
      validation: [{ kind: "route", target: "/plans" }, { kind: "database", target: "plan_versions" }],
      restorationSource: "mem://features/plan-engine + plan-entitlements",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "PAY-005",
      name: "Payment lifecycle and past-due handling",
      category: "Payments",
      source: "mem://features/payments",
      requirement:
        "Checkout, webhook-driven lifecycle and past-due credit pause are handled server-side; access changes only on verified webhook events.",
      behaviour: ["Webhook signature verified before processing", "Past-due pauses credit consumption rather than deleting data"],
      implementation: {
        files: ["src/utils/payments.functions.ts", "src/hooks/usePaddleCheckout.ts", "src/routes/api/public"],
        tables: ["payment_transactions", "payment_events", "stripe_customers", "subscriptions"],
      },
      dependencies: ["PAY-003"],
      validation: [{ kind: "database", target: "payment_events" }, { kind: "manual", target: "Confirm webhook signature verification is present" }],
      restorationSource: "mem://features/payments",
      status: "PASS",
      permanent: "PENDING",
      severity: "CRITICAL",
    },
    {
      id: "PAY-006",
      name: "Owner and admin accounts have free access",
      category: "Credits",
      source: "Approved: 'owner/admin accounts don't need credit barriers'",
      requirement: "Platform owner, co-admin and whitelisted test accounts bypass credit barriers without bypassing metering records.",
      behaviour: ["has_free_access returns true for these accounts", "Usage is still recorded for analytics"],
      implementation: { dbFunctions: ["has_free_access"], tables: ["platform_test_accounts", "staff_codes", "staff_redemptions", "promo_codes", "promo_redemptions"] },
      dependencies: ["ACCT-005"],
      validation: [{ kind: "database", target: "has_free_access" }],
      restorationSource: "public.has_free_access (current)",
      status: "PASS",
      permanent: "PENDING",
    },
  ],
};

export const gateway: RequirementDomain = {
  key: "GW",
  title: "Student Access Gateway",
  summary: "Per-workspace student-access plans, the public /g/:handle gateway and Stripe Connect payouts.",
  coverage: "Built from src/lib/gateway/*, src/components/gateway/*, gateway_* tables and mem://features/gateway-pricing, gateway-stripe-connect.",
  requirements: [
    {
      id: "GW-001",
      name: "Three gateway slots over existing items",
      category: "Gateway",
      source: "src/lib/gateway/items.ts (code-evidenced) + mem://features/gateway-pricing",
      requirement:
        "Every teacher and school owns three gateway slots (free, pro, third). The gateway is an access-control layer over existing platform items — it never introduces new features.",
      behaviour: [
        "Free slot seeds with class notes + assignment and is published.",
        "Pro seeds with every item and is unpublished until priced.",
        "Entitlement snapshots record what a student bought.",
      ],
      implementation: {
        files: ["src/lib/gateway/items.ts"],
        symbols: ["GATEWAY_ITEMS", "SLOT_SEED", "GatewaySlot"],
        routes: ["/g/$handle"],
        tables: ["gateway_plans", "gateway_entitlements", "gateway_payments"],
        dbFunctions: ["gateway_by_handle", "gateway_choose_plan"],
      },
      dependencies: ["PAY-004"],
      validation: [
        { kind: "module", target: "src/lib/gateway/items.ts", expects: ["GATEWAY_ITEMS", "SLOT_SEED"] },
        { kind: "database", target: "gateway_plans" },
      ],
      restorationSource: "src/lib/gateway/items.ts (current, authoritative for the item list)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "GW-002",
      name: "Per-workspace Stripe Connect with 0% platform fee",
      category: "Gateway",
      source: "mem://features/gateway-stripe-connect",
      requirement:
        "Each workspace connects its own payout account; the platform takes 0% fee; access is granted only by webhook, never optimistically.",
      behaviour: ["Payment activation gate blocks selling before onboarding completes", "Webhook-only access grants"],
      implementation: { tables: ["gateway_payout_accounts", "gateway_payments", "gateway_entitlements"] },
      dependencies: ["GW-001", "PAY-005"],
      validation: [{ kind: "database", target: "gateway_payout_accounts" }],
      restorationSource: "mem://features/gateway-stripe-connect",
      status: "PASS",
      permanent: "PENDING",
      severity: "HIGH",
    },
  ],
};

export const adminConsole: RequirementDomain = {
  key: "ADM",
  title: "Platform Admin Console",
  summary: "The owner console: metering, financial ledger, pricing, plans, CMS, assets and impersonation.",
  coverage: "Built from src/pages/admin/*, src/components/admin/*, src/routes/admin/* and mem://features/platform-console, usage-revenue-analytics.",
  requirements: [
    {
      id: "ADM-001",
      name: "Owner-only console with a premium shell",
      category: "Admin",
      source: "mem://features/platform-console + approved 'Admin Dashboard with gold accents'",
      requirement: "Admin routes are reachable only by owner/co-admin, using the premium dashboard shell and its own design tokens.",
      behaviour: ["A non-admin cannot load /admin", "Gold-accented shell distinguishes the console"],
      implementation: { files: ["src/routes/admin/route.tsx", "src/components/admin"], routes: ["/admin"] },
      dependencies: ["ACCT-005"],
      validation: [{ kind: "route", target: "/admin" }, { kind: "manual", target: "Attempt /admin as a teacher and confirm refusal" }],
      restorationSource: "src/routes/admin/route.tsx guard (current)",
      status: "PASS",
      permanent: "PENDING",
      severity: "CRITICAL",
    },
    {
      id: "ADM-002",
      name: "Usage and revenue analytics",
      category: "Admin",
      source: "mem://features/usage-revenue-analytics",
      requirement:
        "The console shows admin-only metering, a financial ledger, credit wallets, promo/staff codes and pricing snapshots.",
      behaviour: ["Figures come from usage_events and the ledger, not estimates"],
      implementation: {
        files: ["src/pages/admin/UsageRevenue.tsx", "src/pages/admin/BillingCosts.tsx", "src/pages/admin/CreditsEconomics.tsx"],
        routes: ["/admin/usage", "/admin/billing", "/admin/credits"],
        tables: ["usage_events", "credit_ledger", "cost_unit_totals", "currency_rates"],
        dbFunctions: ["import_platform_usage"],
      },
      dependencies: ["PAY-001", "ADM-001"],
      validation: [{ kind: "module", target: "src/pages/admin/UsageRevenue.tsx" }],
      restorationSource: "mem://features/usage-revenue-analytics",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "ADM-003",
      name: "Enter Workspace impersonation is logged",
      category: "Admin",
      source: "mem://features/platform-console — owner Enter Workspace impersonation",
      requirement: "An owner may enter any workspace to support it; every entry writes an audit row and the session is clearly marked.",
      behaviour: ["Audit row per entry", "Impersonation is visibly indicated"],
      implementation: { tables: ["admin_impersonation_log"], dbFunctions: ["enter_workspace"] },
      dependencies: ["ADM-001"],
      validation: [{ kind: "database", target: "admin_impersonation_log" }],
      restorationSource: "enter_workspace (current)",
      status: "PASS",
      permanent: "PENDING",
      severity: "HIGH",
    },
    {
      id: "ADM-004",
      name: "Administered content: ads, buildings, CMS, emails",
      category: "Admin",
      source: "Approved across the billboard, homepage, CMS and email work",
      requirement:
        "Billboards, the default building, public site sections, testimonials and platform email templates are all administered from the console.",
      behaviour: ["No hard-coded marketing content", "Email templates and senders are rows"],
      implementation: {
        tables: ["platform_advertisements", "platform_building_default", "site_sections", "site_testimonials", "platform_email_templates", "platform_email_senders", "platform_email_settings"],
      },
      dependencies: ["ADM-001", "RB-005", "SITE-001"],
      validation: [{ kind: "database", target: "platform_email_templates" }],
      restorationSource: "current admin tables",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "ADM-005",
      name: "GPL asset management access",
      category: "Admin",
      source:
        "Approved after the regression: 'The last update removed the ability to edit assets' — access is granted by a manager whitelist.",
      requirement:
        "Asset management access is granted through can_manage_gpl_assets / asset_managers; the owner can whitelist a manager from the console.",
      behaviour: ["Losing the capability must not silently break asset creation", "Access errors say what is missing"],
      implementation: {
        files: ["src/components/admin/assets/AssetManagersCard.tsx", "src/pages/admin/AccessCodesPage.tsx"],
        tables: ["asset_managers", "gpl_assets"],
        dbFunctions: ["can_manage_gpl_assets"],
      },
      dependencies: ["AST-002", "ADM-001"],
      validation: [
        { kind: "database", target: "can_manage_gpl_assets" },
        { kind: "module", target: "src/components/admin/assets/AssetManagersCard.tsx" },
      ],
      restorationSource: "can_manage_gpl_assets + asset_managers (current)",
      status: "PASS",
      severity: "MEDIUM",
      permanent: "PENDING",
      notes:
        "Cleared 2026-08-25: the console screen exists and is reachable — AccessCodesPage renders AssetManagersCard for the asset-manager purpose, so the owner can whitelist and remove a manager there, backed by can_manage_gpl_assets / asset_managers.",
    },
  ],
};

export const assets: RequirementDomain = {
  key: "AST",
  title: "GPL Assets & Media",
  summary: "The hierarchical asset library, sessions/sub-sessions, uploads, background removal and pickers.",
  coverage: "Built from src/components/assets/*, src/components/gpl/*, src/lib/assets/assetLibrary.ts, gpl_asset* / custom_assets / building_assets / game_assets tables.",
  requirements: [
    {
      id: "AST-001",
      name: "Hierarchical asset library",
      category: "Assets",
      source: "Approved: 'COMPLETE GPL ASSET MANAGEMENT SYSTEM REDESIGN'",
      requirement: "Assets are organised in sessions and sub-sessions with usage tracking; official and custom assets are distinguished.",
      behaviour: ["A session groups sub-sessions which group assets", "Usage is recorded so an asset's use is visible"],
      implementation: {
        files: ["src/lib/assets/assetLibrary.ts", "src/components/assets/OfficialAssetSection.tsx", "src/components/assets/AssetFormDialog.tsx"],
        routes: ["/assets"],
        tables: ["gpl_assets", "gpl_asset_sessions", "gpl_asset_subsessions", "gpl_asset_usage", "custom_assets", "game_assets"],
      },
      validation: [{ kind: "route", target: "/assets" }, { kind: "database", target: "gpl_asset_sessions" }],
      restorationSource: "current asset library + tables",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "AST-002",
      name: "Asset manager access without race conditions",
      category: "Assets",
      source: "Approved: 'Asset Manager FIX ACCESS + ASSET CREATION WORKFLOW'",
      requirement: "Asset manager access is resolved after the session is ready; an auth race must never present the library as forbidden.",
      behaviour: ["No false 'no access' on first load", "Creation workflow is reachable for permitted managers"],
      implementation: { files: ["src/components/assets", "src/lib/assets/assetLibrary.ts"], dbFunctions: ["can_manage_gpl_assets"] },
      dependencies: ["PLAT-003", "ADM-005"],
      validation: [{ kind: "behaviour", target: "Hard-reload /assets as a permitted manager; access must hold" }],
      restorationSource: "auth race fix in the asset manager (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "AST-003",
      name: "Uploads preview immediately and classify correctly",
      category: "Assets",
      source: "Fix approved after: 'after removing the background it came out blank'",
      requirement:
        "An uploaded or processed asset is classified by its real media type (processed WebM is video) and previews immediately, including from private storage via a signed URL.",
      behaviour: ["mediaTypeOfAsset recognises processed video", "Extensions are normalised", "No broken-image placeholder for a valid video"],
      implementation: {
        files: ["src/components/assets/OfficialAssetSection.tsx", "src/lib/assets/assetLibrary.ts"],
        symbols: ["mediaTypeOfAsset"],
      },
      dependencies: ["AST-005"],
      validation: [{ kind: "behaviour", target: "Upload and process a video; both cards must render as video" }],
      restorationSource: "mediaTypeOfAsset + extension normalisation (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "AST-004",
      name: "One media picker for GPL assets",
      category: "Assets",
      source: "Approved: 'all my uploads… should add upload from device, upload from my GPL assets'",
      requirement: "A single picker component browses GPL media by session/sub-session and is offered wherever media is chosen.",
      behaviour: ["Supports storage paths, external URLs and signed previews"],
      implementation: { files: ["src/components/assets/MyGplMediaPicker.tsx"] },
      dependencies: ["AST-001"],
      validation: [{ kind: "module", target: "src/components/assets/MyGplMediaPicker.tsx" }],
      restorationSource: "MyGplMediaPicker (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "AST-005",
      name: "Background removal preserves quality and produces straight alpha",
      category: "Assets",
      source:
        "Approved: 'the background remover should not affect the video. It must cut it carefully' and then 'it should blend, not sit on black'",
      requirement:
        "Chroma-key background removal runs on new uploads, keeps dimensions, detail and audio, emits straight-alpha transparent WebM, and falls back to the original when the video is not keyable.",
      behaviour: [
        "Edge-softness control, progress and cancellation.",
        "premultipliedAlpha: false, canvas cleared per frame.",
        "Original is preserved; processing produces a new asset.",
      ],
      implementation: { files: ["src/lib/games/videoChromaCut.ts", "src/components/games/ChromaVideo.tsx", "src/components/assets/AssetFormDialog.tsx"] },
      dependencies: ["ADV-008"],
      validation: [{ kind: "behaviour", target: "Process a keyable video and composite it over colour; corners must be transparent" }],
      restorationSource: "videoChromaCut.ts (current, straight alpha)",
      status: "PASS",
      permanent: "PENDING",
    },
  ],
};

export const aiLayers: RequirementDomain = {
  key: "AI",
  title: "AI Layers, Co-Pilot & Math Engine",
  summary:
    "The three-layer AI split, the fixed Co-Pilot procedure, the independent mathematics engine and the content-integrity protocol.",
  coverage:
    "Built from src/lib/copilot/conversation.ts, src/lib/lessonnotes/aiMode.ts, src/lib/mathengine/*, supabase/functions/notebook-ai/* standards and mem://features/math-engine.",
  requirements: [
    {
      id: "AI-001",
      name: "Three AI layers, strictly separated",
      category: "AI",
      source: "mem://index.md Core rule + mem://features/math-engine",
      requirement:
        "Lovable builds software; the MathGPL Co-Pilot understands the application; the MathGPL Math Engine is the only producer of teacher-facing mathematics, verified in code.",
      behaviour: [
        "No teacher-facing mathematics is emitted without engine verification.",
        "Co-Pilot never invents mathematics itself.",
        "Lesson modes select which layer is active.",
      ],
      implementation: { files: ["src/lib/mathengine", "src/lib/copilot/conversation.ts", "src/lib/lessonnotes/aiMode.ts"] },
      dependencies: ["AI-005"],
      validation: [{ kind: "module", target: "src/lib/mathengine/verify.ts" }],
      restorationSource: "mem://features/math-engine (authoritative)",
      status: "PASS",
      permanent: "PENDING",
      severity: "CRITICAL",
    },
    {
      id: "AI-002",
      name: "AI as editor, in non-blocking sidebars",
      category: "AI",
      source: "Approved with the lesson mode rebuild",
      requirement:
        "In Manual mode AI cleans formatting and structure rather than authoring content, and all AI panels are non-modal sidebars that never block the document.",
      behaviour: ["The document stays editable while AI works", "Accepting an edit replaces structured content atomically"],
      implementation: {
        files: ["src/components/lessonnotes/AiSettingsPanel.tsx", "src/lib/lessonnotes/materializeDirectives.ts", "src/hooks/useAiEditBridge.tsx"],
      },
      dependencies: ["LN-004", "MATH-001"],
      validation: [{ kind: "behaviour", target: "Accept an AI edit on a matrix or table and confirm the structure survives" }],
      restorationSource: "materializeDirectives + AiSettingsPanel (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "AI-003",
      name: "Content integrity: QUESTION_LOCK",
      category: "AI",
      source: "mem://pedagogy/integrity + supabase/functions/notebook-ai/integrityStandard.ts",
      requirement:
        "The teacher's problem is immutable. solution[0] restates it verbatim; the AI may never substitute a different equation, numbers, signs, variables or exponents. Enforced in the prompt and by a runtime guard.",
      behaviour: [
        "Runtime guard rejects a mismatched generation.",
        "Question Inheritance requires inheritedContext: true and returns 422 on mismatch.",
      ],
      implementation: {
        files: [
          "supabase/functions/notebook-ai/integrityStandard.ts",
          "supabase/functions/notebook-ai/inheritanceStandard.ts",
          "supabase/functions/notebook-ai/index.ts",
        ],
        symbols: ["INTEGRITY_STANDARD"],
      },
      dependencies: ["AI-001"],
      validation: [
        { kind: "module", target: "supabase/functions/notebook-ai/integrityStandard.ts", expects: ["INTEGRITY_STANDARD"] },
        { kind: "behaviour", target: "Generate a solution and confirm line 1 restates the question verbatim" },
      ],
      restorationSource: "integrityStandard.ts (immutable standard, current)",
      status: "PASS",
      permanent: "PENDING",
      severity: "CRITICAL",
    },
    {
      id: "AI-004",
      name: "Pedagogical rendering standard",
      category: "AI",
      source: "mem://pedagogy/master + docs/pedagogical_reference_master_v9.docx",
      requirement:
        "Generated mathematics follows the Master Pedagogical Reference: one micro-step per line, no skipped transitions, stacked fractions, no calculator or coding syntax.",
      behaviour: ["Every transition is shown", "No inline slash fractions in teacher-facing output"],
      implementation: {
        files: [
          "supabase/functions/notebook-ai/pedagogyReference.ts",
          "supabase/functions/notebook-ai/renderingStandard.ts",
          "supabase/functions/notebook-ai/benchmarkStandard.ts",
          "docs/MathGPL Knowledge Base/README.md",
        ],
        symbols: ["PEDAGOGY_REFERENCE"],
      },
      dependencies: ["AI-003", "MATH-001"],
      validation: [{ kind: "module", target: "supabase/functions/notebook-ai/pedagogyReference.ts", expects: ["PEDAGOGY_REFERENCE"] }],
      restorationSource: "pedagogyReference.ts + docs/pedagogical_reference_master_v9.docx (immutable reference)",
      status: "PASS",
      permanent: "PENDING",
      severity: "CRITICAL",
    },
    {
      id: "AI-005",
      name: "Independent, verified mathematics",
      category: "AI",
      source: "Approved: 'Do not use Lovable AI's mathematical reasoning. The mathematical engine must be independently grounded.'",
      requirement:
        "Mathematics is produced and checked deterministically in src/lib/mathengine and the notebook-ai verifiers; a claim is displayed only if it verifies.",
      behaviour: ["Surd and superscript handling is explicit", "Unverifiable output is regenerated, not shown"],
      implementation: {
        files: [
          "src/lib/mathengine/verify.ts",
          "supabase/functions/notebook-ai/completenessVerifier.ts",
          "supabase/functions/notebook-ai/floatingVerifier.ts",
          "supabase/functions/floating-reason/verifier.ts",
        ],
      },
      validation: [{ kind: "test", target: "src/lib/mathengine/__tests__" }],
      restorationSource: "src/lib/mathengine/* (current)",
      status: "PASS",
      permanent: "PENDING",
      severity: "CRITICAL",
    },
    {
      id: "AI-006",
      name: "The fixed ten-step Co-Pilot procedure",
      category: "AI",
      source:
        "Approved verbatim: greeting → structure → additional information → analysis → build → interaction → interrupt → number vs math change → position awareness → interaction feel. 'Do not change the established Copilot procedure.'",
      requirement:
        "The Co-Pilot follows those ten steps as a state machine, persists its conversation per lesson note, and builds sequentially Question → Diagram → Solution with 'zero' counts meaning skip.",
      behaviour: [
        "'Proceed' means work independently through the remaining stages.",
        "A Blueprint Review stage precedes building.",
        "Conversation survives a reload; the session does not reset.",
        "A 'New subtopic' action restarts the cycle at the end of a lesson.",
      ],
      implementation: {
        files: ["src/lib/copilot/conversation.ts", "src/lib/copilot", "supabase/functions/notebook-ai/copilotTrainingStandard.ts"],
        tables: ["notebook_copilot_sessions", "notebook_copilot_messages"],
      },
      dependencies: ["AI-001", "LN-004"],
      validation: [
        { kind: "database", target: "notebook_copilot_sessions" },
        { kind: "module", target: "src/lib/copilot/conversation.ts" },
      ],
      restorationSource: "conversation.ts state machine + copilotTrainingStandard.ts (current)",
      status: "PASS",
      permanent: "PENDING",
      severity: "HIGH",
    },
    {
      id: "AI-007",
      name: "Request lifecycle with a real Cancel",
      category: "AI",
      source: "Approved: 'Implement request lifecycle (Thinking, Generating, Validating, Ready) with a real Cancel operation (AbortController). Failure must not block the editor.'",
      requirement:
        "Every AI request exposes its lifecycle state and can be cancelled with AbortController. A failed or cancelled request releases the workspace immediately.",
      behaviour: ["Cancel aborts the in-flight request", "No overlay can outlive its request", "Failures surface as messages, not freezes"],
      implementation: { files: ["src/lib/copilot/conversation.ts", "src/lib/ai"], symbols: ["AbortController"] },
      dependencies: ["STAB-002"],
      validation: [{ kind: "behaviour", target: "Start a generation, press Cancel, confirm the editor is usable at once" }],
      restorationSource: "AbortController lifecycle in conversation.ts (current)",
      status: "PASS",
      permanent: "PENDING",
      severity: "HIGH",
    },
    {
      id: "AI-008",
      name: "Reasoning layers and preference panel",
      category: "AI",
      source: "Approved: 'Layer 1 (Always On reasoning), Layer 2 (Optional switches)'",
      requirement: "Layer 1 reasoning is always on; Layer 2 behaviours are optional switches the teacher controls.",
      behaviour: ["Switch state persists per teacher"],
      implementation: { files: ["src/components/lessonnotes/AiSettingsPanel.tsx"] },
      dependencies: ["AI-002"],
      validation: [{ kind: "module", target: "src/components/lessonnotes/AiSettingsPanel.tsx" }],
      restorationSource: "AiSettingsPanel (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "AI-009",
      name: "Session-aware generation context",
      category: "AI",
      source: "Approved: 'REBUILD THE AI QUESTION GENERATION AND CONTEXT WORKFLOW to be document/session-context aware'",
      requirement: "Generation reads the surrounding document/session context so new content continues the lesson instead of restarting it.",
      behaviour: ["Context is assembled deterministically from the document", "Solutions start under their session heading"],
      implementation: { files: ["src/lib/lessonnotes/sessionContext.ts"], symbols: ["sessionContext"] },
      dependencies: ["AI-003", "LN-008"],
      validation: [{ kind: "module", target: "src/lib/lessonnotes/sessionContext.ts" }],
      restorationSource: "sessionContext.ts (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "AI-010",
      name: "AI failures are explained, not raw",
      category: "AI",
      source: "Approved: 'Fix Lesson Note AI errors (402/429 prompts)'",
      requirement: "Credit and rate-limit failures produce a plain-language message and a retry path, never a raw status code.",
      behaviour: ["402 explains credits", "429 explains rate limiting"],
      implementation: { files: ["src/lib/ai", "src/lib/copilot/conversation.ts"] },
      dependencies: ["PAY-001", "AI-007"],
      validation: [{ kind: "manual", target: "Trigger a rate limit and inspect the message" }],
      restorationSource: "current AI error handling",
      status: "PASS",
      permanent: "PENDING",
    },
  ],
};

export const stability: RequirementDomain = {
  key: "STAB",
  title: "Stability, Reliability & Access",
  summary: "No single point of failure: resource registry, watchdogs, local drafts and access recovery.",
  coverage: "Built from src/lib/stability/*, src/components/common/StabilityWatchdog.tsx, docs/reliability/access-runbook.md.",
  requirements: [
    {
      id: "STAB-001",
      name: "Live resource registry",
      category: "Stability",
      source: "Approved in the reliability master prompt; documented in src/lib/stability/registry.ts",
      requirement:
        "Every managed timer, poller, subscription and listener registers in the resource registry so leaks are measurable, with a console debug hook.",
      behaviour: ["Counts return to baseline after leaving a page", "__mathgplStability exposes counts/list/oldest"],
      implementation: { files: ["src/lib/stability/registry.ts"], symbols: ["trackResource", "releaseResource", "resourceCounts", "exposeStabilityDebug"] },
      validation: [{ kind: "module", target: "src/lib/stability/registry.ts", expects: ["trackResource", "resourceCounts"] }],
      restorationSource: "src/lib/stability/registry.ts (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "STAB-002",
      name: "The workspace must never freeze",
      category: "Stability",
      source:
        "Approved repeatedly: 'Solve workspace hooking/freezing', 'Fix the frozen/paused state', 'switching between sections doesn't reset, pause, or lock the workspace'",
      requirement:
        "No overlay, request, layout effect or navigation may leave the lesson-note or board workspace unresponsive. Layout must not loop.",
      behaviour: [
        "Overlays are released when their request ends, fails or is cancelled.",
        "Section switching never locks the document.",
        "A watchdog detects a stalled workspace.",
      ],
      implementation: {
        files: ["src/components/common/StabilityWatchdog.tsx", "src/lib/lessonnotes/sessionLayout.ts", "src/lib/copilot/conversation.ts"],
      },
      dependencies: ["STAB-001", "AI-007"],
      validation: [
        { kind: "behaviour", target: "Switch sections 20 times and confirm the workspace stays responsive" },
        { kind: "test", target: "src/lib/lessonnotes/__tests__/sessionLayoutBudget.test.ts" },
      ],
      restorationSource: "StabilityWatchdog + sessionLayout loop fix (current)",
      status: "PARTIAL",
      severity: "CRITICAL",
      permanent: "PENDING",
      notes:
        "PARTIAL: multiple specific freezes were fixed, but there is no automated guard against the class of defect. This is the highest-value Section I test to add.",
    },
    {
      id: "STAB-003",
      name: "Work is never lost",
      category: "Stability",
      source: "Approved in the reliability master prompt (localDraft protection)",
      requirement: "Unsaved work is mirrored locally and flushed on unload, so a network or auth failure cannot destroy it.",
      behaviour: ["Local draft restores after a crash", "beforeunload flushes pending changes"],
      implementation: { files: ["src/lib/stability/localDraft.ts", "src/components/lessonnotes/DocumentEditor.tsx"] },
      dependencies: ["DIAG-001"],
      validation: [{ kind: "module", target: "src/lib/stability/localDraft.ts" }],
      restorationSource: "localDraft.ts (current)",
      status: "PASS",
      permanent: "PENDING",
      severity: "CRITICAL",
    },
    {
      id: "STAB-004",
      name: "Access runbook",
      category: "Stability",
      source: "Approved with the access/trust work",
      requirement: "A written runbook covers domain, certificate and access incidents so recovery does not depend on memory.",
      behaviour: ["Runbook is in the repository and current"],
      implementation: { files: ["docs/reliability/access-runbook.md"] },
      dependencies: ["PLAT-005", "PLAT-006"],
      validation: [{ kind: "module", target: "docs/reliability/access-runbook.md" }],
      restorationSource: "docs/reliability/access-runbook.md",
      status: "PASS",
      permanent: "PENDING",
    },
  ],
};

export const design: RequirementDomain = {
  key: "DES",
  title: "Design System & Editing Conventions",
  summary: "Legibility rules, the universal asset-editing rule and the premium theme conventions.",
  coverage: "Built from src/styles.css, mem://design/universal-editing-rule and the design decisions recorded across the history.",
  requirements: [
    {
      id: "DES-001",
      name: "Assets are legible by default",
      category: "Design",
      source: "mem://design/universal-editing-rule",
      requirement:
        "Every asset renders legibly by default: dark ink, visible borders, readable font size. No white-on-white or low-contrast surfaces.",
      behaviour: ["Chat, panels and diagrams all meet contrast expectations by default"],
      implementation: { files: ["src/styles.css", "src/components/lessonnotes", "src/components/smartboard"] },
      validation: [{ kind: "manual", target: "Review new surfaces for contrast" }],
      restorationSource: "mem://design/universal-editing-rule (authoritative)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "DES-002",
      name: "Universal asset editing lives in the right-hand panel",
      category: "Design",
      source: "mem://design/universal-editing-rule",
      requirement:
        "ALL asset settings live in the right-hand Properties Panel via useRegisterAssetEditor. No floating popovers, inline Edit chips or bottom toolbars.",
      behaviour: [
        "An asset registers its editor; the panel renders it.",
        "An Edit affordance may appear on the object, but the settings themselves open in the panel.",
      ],
      implementation: { files: ["src/hooks/useAssetSelection.tsx", "src/components/lessonnotes"], symbols: ["useRegisterAssetEditor"] },
      dependencies: ["GEO-006"],
      validation: [{ kind: "manual", target: "Select several asset types and confirm settings appear only in the right panel" }],
      restorationSource: "mem://design/universal-editing-rule (authoritative)",
      status: "PASS",
      permanent: "PENDING",
      severity: "MEDIUM",
    },
    {
      id: "DES-003",
      name: "Edit affordance timing on living diagrams",
      category: "Design",
      source:
        "Approved: 'clicking towards the end of the bar chart shows Edit; the edit button disappears after 10 seconds of inactivity; the right-hand panel remains until I close it'",
      requirement:
        "The on-object Edit affordance auto-hides after 10 seconds of inactivity, while the properties panel it opened stays until the teacher closes it.",
      behaviour: ["Panel persistence is independent of the button's visibility", "Each diagram instance is tracked separately"],
      implementation: { files: ["src/components/lessonnotes/LivingDiagram.tsx", "src/hooks/useAutoHide.ts", "src/hooks/useHoverIdleVisibility.ts"] },
      dependencies: ["DES-002"],
      validation: [{ kind: "behaviour", target: "Open the panel, wait 10s: button hides, panel stays" }],
      restorationSource: "LivingDiagram + useAutoHide (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "DES-004",
      name: "Premium themes per surface",
      category: "Design",
      source: "Approved: 'Teacher Workspace: Premium dark theme', 'Premium white cards on navy', gold-accented admin console",
      requirement: "Each surface family keeps its established premium theme; colours come from tokens, never hard-coded utilities.",
      behaviour: ["No hard-coded colour utilities in components", "Themes are distinguishable per surface family"],
      implementation: { files: ["src/styles.css"] },
      validation: [{ kind: "manual", target: "Grep components for hard-coded colour utilities" }],
      restorationSource: "src/styles.css tokens",
      status: "PARTIAL",
      severity: "LOW",
      permanent: "PENDING",
      notes: "PARTIAL: token discipline was not verified component-by-component in this pass.",
    },
  ],
};
