import type { RequirementDomain } from "../types";

export const smartboard: RequirementDomain = {
  key: "SB",
  title: "Smartboard (Two-Board Architecture)",
  summary:
    "Deterministic session recognition, Board A presentation, Board B as an independent working copy, writing/marking and the tool rails.",
  coverage:
    "Built from src/components/smartboard/* (49 components), src/lib/smartboard/* and the archived Board A/Board B plans.",
  requirements: [
    {
      id: "SB-001",
      name: "Deterministic session recognition (no AI)",
      category: "Smartboard",
      source: "Approved: 'The system must understand session boundaries deterministically without AI to drive Smartboard presentation.'",
      requirement:
        "Session/beat boundaries are computed from the document structure by code. AI is never involved in deciding what a board page contains.",
      behaviour: ["Example sessions fold their Solution into the preceding question", "Boundaries are stable across reloads"],
      implementation: {
        files: ["src/lib/smartboard/presentation.ts", "src/lib/smartboard/presentationPlan.ts", "src/lib/smartboard/lessonPhase.ts", "src/lib/smartboard/lessonLines.ts"],
      },
      dependencies: ["LN-008"],
      validation: [
        { kind: "test", target: "src/lib/smartboard/__tests__ (existing presentation/navigation tests)" },
        { kind: "module", target: "src/lib/smartboard/presentation.ts" },
      ],
      restorationSource: "src/lib/smartboard/presentation.ts (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "SB-002",
      name: "Solution diagrams are excluded from the student board, tables are not",
      category: "Smartboard",
      source:
        "Approved special rule: '2D/3D diagrams inside Solutions must NOT display on the student Smartboard (teacher handles separately), but tables should still appear.'",
      requirement:
        "On the student-facing board, diagrams that live inside a Solution are withheld while tables from the same Solution are shown.",
      behaviour: ["Teacher reveals solution diagrams separately", "Tables always render"],
      implementation: { files: ["src/components/smartboard/PresentationView.tsx"] },
      dependencies: ["DIAG-004", "TBL-001"],
      validation: [{ kind: "behaviour", target: "Open a solution with a diagram and a table on the student board" }],
      restorationSource: "Solution filtering in PresentationView (current)",
      status: "PASS",
      permanent: "PENDING",
      notes:
        "Tension to confirm: DIAG-004 restores inline diagrams on Board A for the teacher view. This requirement governs the student-facing board. UNKNOWN — REQUIRES HUMAN CONFIRMATION that both rules are simultaneously honoured in the current build.",
      severity: "HIGH",
    },
    {
      id: "SB-003",
      name: "Board B is an independent duplicate of the lesson note",
      category: "Smartboard",
      source: "Approved: 'REDESIGN BOARD B AS A DUPLICATE OF LESSON NOTES' — a working copy whose changes never touch the note",
      requirement:
        "Board B is a complete, persistent, independent duplicate of the lesson note used for rough work. Edits on Board B never modify the lesson note. The old Calculator/Conversion companion was removed.",
      behaviour: ["Identity remapping on duplication", "Board B persists between visits", "Board A is unchanged by this feature"],
      implementation: {
        files: ["src/lib/smartboard/duplicateNote.ts", "src/components/smartboard/CompanionNoteBoard.tsx", "src/components/smartboard/InteractiveBoard.tsx"],
        symbols: ["duplicateNote"],
      },
      dependencies: ["SB-006"],
      validation: [
        { kind: "module", target: "src/lib/smartboard/duplicateNote.ts" },
        { kind: "behaviour", target: "Edit Board B, reopen the lesson note, confirm the note is unchanged" },
      ],
      restorationSource: "duplicateNote.ts + CompanionNoteBoard.tsx (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "SB-004",
      name: "Structures expand on the board",
      category: "Smartboard",
      source: "Approved: matrices/roots/fractions expand into editable structures when clicked on the board",
      requirement:
        "A compact structure chip on the board expands into a pre-filled editable structure parsed from the saved representation, never re-typed by hand.",
      behaviour: ["latexToTree parses the stored form", "Expanded structure is editable in place"],
      implementation: { files: ["src/components/smartboard/PresentationView.tsx", "src/lib/smartboard/mathTree.ts", "src/components/smartboard/MathTreeRender.tsx"], symbols: ["latexToTree"] },
      dependencies: ["MATH-004", "MATH-006"],
      validation: [{ kind: "test", target: "matrix/structure parsing tests" }],
      restorationSource: "latexToTree expansion path (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "SB-005",
      name: "Notes reveal and Review Properties",
      category: "Smartboard",
      source: "Approved: 'Click on note icon on smart board should reveal diagram' + Smartboard Review Properties",
      requirement:
        "The board exposes a notes reveal for unhighlighted note content (including diagrams) and a Review Properties panel with hit-layer highlighting bound to geometry identity.",
      behaviour: ["Note icon reveals the attached note object", "Selecting a property highlights the exact part"],
      implementation: { files: ["src/components/smartboard/ReviewPropertiesPanel.tsx", "src/components/smartboard/ReviewableBoardDiagram.tsx", "src/lib/smartboard/reviewProperties.tsx"] },
      dependencies: ["GPROP-001", "FLT-005"],
      validation: [{ kind: "behaviour", target: "Use the note icon on a beat with an attached diagram" }],
      restorationSource: "ReviewPropertiesPanel + reviewProperties.tsx (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "SB-006",
      name: "One environment, two synchronised boards",
      category: "Smartboard",
      source: "Approved: 'TWO-BOARD SMARTBOARD ARCHITECTURE… do not build two separate screens'",
      requirement:
        "Board A (teaching/presentation) and Board B (working) live in one environment and stay on the same lesson position via a shared sectionId/sectionLabel.",
      behaviour: ["Moving Board A moves Board B's position context", "Neither board is a separate route/screen"],
      implementation: { files: ["src/components/smartboard/SmartboardRoot.tsx", "src/components/smartboard/InteractiveBoard.tsx", "src/lib/smartboard/presentation.ts"], symbols: ["sectionId", "sectionLabel"] },
      dependencies: ["SB-001"],
      validation: [{ kind: "module", target: "src/components/smartboard/SmartboardRoot.tsx" }],
      restorationSource: "sectionId/sectionLabel sync (kept by the 2026-08-24 revert)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "SB-007",
      name: "Writing, marking and student mirroring",
      category: "Smartboard",
      source: "Approved across the writing/marking work; 'Student Line must mirror student math object'",
      requirement:
        "The board supports free writing, structured writing, line status, marking and hints, and a student line mirrors the student's own math object rather than a re-typed copy.",
      behaviour: ["Line status rail reflects check results", "Student math tree is mirrored, not re-parsed"],
      implementation: {
        files: [
          "src/components/smartboard/WritingSurface.tsx",
          "src/components/smartboard/WritingSensor.tsx",
          "src/components/smartboard/LineStatusRail.tsx",
          "src/components/smartboard/PresenterMath.tsx",
        ],
      },
      dependencies: ["ASMT-002", "MATH-006"],
      validation: [{ kind: "behaviour", target: "Write a student line and confirm the mirrored structure matches" }],
      restorationSource: "PresenterMath mirroring (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "SB-008",
      name: "Board tools: diagram, tables, graph, calculator, conversion",
      category: "Smartboard",
      source: "Approved: 'Smartboard — Final Tool Integration: Diagram (2D/3D menu), Tables, Graph, Calculator, Conversion' with Small/Medium/Full span",
      requirement: "Board tools are reachable from the rails, insert real objects, and offer Small/Medium/Full span sizing.",
      behaviour: ["Diagram menu offers 2D and 3D", "Span choice persists per object"],
      implementation: { files: ["src/components/smartboard/RightTools.tsx", "src/components/smartboard/BoardToolLayer.tsx", "src/components/smartboard/StylesRail.tsx"] },
      dependencies: ["G3D-001", "CHT-002"],
      validation: [{ kind: "manual", target: "Insert each tool and set its span" }],
      restorationSource: "current tool rails",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "SB-009",
      name: "Back returns the way you came",
      category: "Smartboard",
      source: "Archived plan: 'smartboard back button returns the way you came' (2026-08-25)",
      requirement: "The board's back control returns to the surface that opened it, not to a fixed default page.",
      behaviour: ["Entry origin is remembered", "Deep links have a sensible fallback"],
      implementation: { files: ["src/components/smartboard/TopBar.tsx", "src/lib/smartboard/boardScope.ts"] },
      validation: [{ kind: "behaviour", target: "Open the board from a class and from a lesson note; back must differ" }],
      restorationSource: ".lovable/drafts/.../smartboard-back-button-returns-the-way-you-came-2026-08-25/01-plan.md",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "SB-010",
      name: "Board state persists per class",
      category: "Smartboard",
      source: "code-evidenced (class_smartboard_state, assessment_board_state, assessment_question_board_state)",
      requirement: "Board state is stored per class/assessment so reopening resumes exactly where the teacher stopped.",
      behaviour: ["Reopening restores written work and position"],
      implementation: { tables: ["class_smartboard_state", "assessment_board_state", "assessment_question_board_state"], files: ["src/hooks/useSmartboardSync.ts"] },
      dependencies: ["CLS-002"],
      validation: [{ kind: "database", target: "class_smartboard_state" }],
      restorationSource: "current board state tables",
      status: "PASS",
      permanent: "PENDING",
    },
  ],
};

export const floating: RequirementDomain = {
  key: "FLT",
  title: "Floating Numbers Workflow",
  summary:
    "Highlighting a solution into floating numbers, the question-scoped student board, evaluation and the notes-only path.",
  coverage:
    "Built from src/pages/FloatingNumbersPage.tsx, FloatingPreparationPage.tsx, FloatingTestBoardPage.tsx, src/lib/floating/* and src/lib/smartboard/floating*.ts.",
  requirements: [
    {
      id: "FLT-001",
      name: "The Selection Law",
      category: "Floating numbers",
      source:
        "Approved: 'SOLUTION → FLOATING HIGHLIGHTING PAGE → (HIGHLIGHTED → FLOATING GENERATING → FLOATING NUMBERS) OR (NOT HIGHLIGHTED → NOTES → SMARTBOARD NOTES → DIAGRAMS)'",
      requirement:
        "Only highlighted content becomes floating numbers. Unhighlighted content becomes notes. There is no fallback that derives floating lines from unhighlighted text.",
      behaviour: ["No implicit line derivation", "notesOnlyRows carries the unhighlighted remainder"],
      implementation: { files: ["src/pages/FloatingNumbersPage.tsx", "src/lib/floating/highlightEngine.ts"], symbols: ["notesOnlyRows"] },
      dependencies: ["LN-006"],
      validation: [{ kind: "behaviour", target: "Highlight nothing and confirm no floating lines are produced" }],
      restorationSource: "Selection Law implementation in FloatingNumbersPage (current)",
      status: "PASS",
      permanent: "PENDING",
      severity: "HIGH",
    },
    {
      id: "FLT-002",
      name: "The floating page never reinterprets the solution",
      category: "Floating numbers",
      source: "Approved: 'The floating view must not reconstruct or reinterpret the solution.'",
      requirement:
        "Floating surfaces display the same solution objects — diagram-free per DIAG-005, but with identical math notation, fractions, labels and formatting, carried over losslessly.",
      behaviour: ["No re-parsing from rendered text", "Structures render as photocopies of the note"],
      implementation: {
        files: ["src/lib/floating/solutionItems.ts", "src/lib/lessonnotes/mathStructureLatex.ts", "src/components/floating/EquationAtoms.tsx", "src/pages/FloatingPreparationPage.tsx"],
        symbols: ["renderMathInline"],
      },
      dependencies: ["MATH-006", "MATH-001"],
      validation: [{ kind: "behaviour", target: "Compare a solution line in the note and on the floating prep page" }],
      restorationSource: "mathStructureLatex + EquationAtoms rendering (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "FLT-003",
      name: "Question-scoped student board with reset between questions",
      category: "Floating numbers",
      source: "Approved: 'Connect Floating Numbers to a question-scoped Student Smartboard… Test state must reset between questions.'",
      requirement:
        "The floating test board is scoped strictly to the current question/solution, reuses writing/marking/scoring/hints, and resets its state when the question changes.",
      behaviour: ["No content from another question can appear", "Attempt lifecycle resets cleanly"],
      implementation: { files: ["src/pages/FloatingTestBoardPage.tsx", "src/lib/floating/testBoard.ts"] },
      dependencies: ["LN-008", "ASMT-002"],
      validation: [{ kind: "behaviour", target: "Move to the next question and confirm the board resets" }],
      restorationSource: "FloatingTestBoardPage scoping (current)",
      status: "PASS",
      permanent: "PENDING",
      severity: "HIGH",
      notes:
        "History: a defect once showed another problem's solution here. The fix was durable session identity (LN-008). Keep that dependency.",
    },
    {
      id: "FLT-004",
      name: "Atomic structures stay atomic in floating",
      category: "Floating numbers",
      source: "Corrected requirement: matrices behave like roots/fractions, not like cell grids",
      requirement:
        "Matrices, roots, integrals and summations appear as single atomic items on floating surfaces; only tables branch into cells.",
      behaviour: ["Matrix shows its dimensions compactly", "No matrix cell becomes its own floating number"],
      implementation: { files: ["src/pages/FloatingNumbersPage.tsx", "src/components/smartboard/FloatingWorkspace.tsx", "src/components/smartboard/FloatingNumberPanel.tsx"], symbols: ["ensureAtomicMatrixFiller"] },
      dependencies: ["MATH-004", "TBL-002"],
      validation: [{ kind: "test", target: "matrix atomicity tests" }],
      restorationSource: "ensureAtomicMatrixFiller (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "FLT-005",
      name: "Evaluation replaces Reasoning; marks come from floating evaluation",
      category: "Floating numbers",
      source: "Approved: 'Rename Reasoning to Evaluation' + 'Use Floating Number Evaluation for marks'",
      requirement: "The teacher-facing panel is called Evaluation, and marks are derived from the floating-number evaluation, not typed by hand.",
      behaviour: ["No surface still says 'Reasoning' for this panel", "Marks trace back to evaluated lines"],
      implementation: { files: ["src/components/smartboard/TeacherEvaluationPanel.tsx", "src/lib/floating/verifier.ts"] },
      dependencies: ["ASMT-003"],
      validation: [
        { kind: "manual", target: "Confirm the panel label reads Evaluation everywhere" },
        { kind: "module", target: "src/components/smartboard/TeacherEvaluationPanel.tsx" },
      ],
      restorationSource: "current panel + floating verifier",
      status: "PASS",
      severity: "LOW",
      permanent: "PENDING",
      notes:
        "Cleared 2026-08-25: the panel file, its imports and its remaining internal wording were renamed to Evaluation (src/components/smartboard/TeacherEvaluationPanel.tsx); a text search for 'Reasoning' now returns no visible label, badge or heading on this surface.",
    },
    {
      id: "FLT-006",
      name: "Check Line identifies issues without giving answers",
      category: "Floating numbers",
      source: "Approved: 'Improve Check Line System: identify issues without answers'",
      requirement: "Checking a line names what is wrong (or that something is wrong) without revealing the correct value.",
      behaviour: ["No answer leakage in the message", "Deterministic verification, not an AI opinion"],
      implementation: { files: ["src/lib/smartboard/lineValidator.ts", "src/lib/mathengine/verify.ts", "src/lib/floating/verifier.ts"] },
      dependencies: ["AI-005"],
      validation: [{ kind: "test", target: "src/lib/mathengine/__tests__ (verification tests)" }],
      restorationSource: "lineValidator + mathengine/verify (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "FLT-007",
      name: "Floating archive and law library",
      category: "Floating numbers",
      source: "code-evidenced (floating_law_library, floating_law_drafts, floating archive panel)",
      requirement: "Discovered floating laws and past floating work are archived and retrievable, with drafts separated from the published library.",
      behaviour: ["Drafts are not visible as library laws", "Archive is browsable per note"],
      implementation: {
        files: ["src/components/floating/FloatingArchivePanel.tsx", "src/lib/floating/lawDiscovery.ts"],
        tables: ["floating_law_library", "floating_law_drafts", "floating_generations", "floating_chip_snapshots"],
      },
      validation: [{ kind: "database", target: "floating_law_library" }],
      restorationSource: "current floating tables",
      status: "PASS",
      permanent: "PENDING",
    },
  ],
};

export const slides: RequirementDomain = {
  key: "SLD",
  title: "Slides & Presentation",
  summary: "The Note → Slide → Canvas → Preview → Exit pipeline with capture and media import.",
  coverage: "Built from src/components/lessonnotes/SlidePanel.tsx, src/components/slides/SlidePlayer.tsx, notebook_slide* tables.",
  requirements: [
    {
      id: "SLD-001",
      name: "Note → Slide → Canvas → Preview → Exit",
      category: "Slides",
      source: "Approved: 'REBUILD SLIDE / PRESENTATION SYSTEM. Note -> Slide -> Canvas -> Preview -> Exit.'",
      requirement: "Slides are built on a Canvas model with that exact five-step flow; a slide is not a screenshot of the note.",
      behaviour: ["Canvas holds positioned items", "Preview plays the deck", "Exit returns to the note"],
      implementation: {
        files: ["src/components/lessonnotes/SlidePanel.tsx", "src/components/slides/SlidePlayer.tsx"],
        tables: ["notebook_slide_decks", "notebook_slides", "notebook_slide_items"],
      },
      dependencies: ["LN-002"],
      validation: [{ kind: "database", target: "notebook_slide_items" }, { kind: "module", target: "src/components/slides/SlidePlayer.tsx" }],
      restorationSource: "notebook_slide* tables + SlidePlayer (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "SLD-002",
      name: "Independent scrolling for canvas and note",
      category: "Slides",
      source: "Approved: 'Fix the Slide Canvas scrolling architecture'",
      requirement: "The slide canvas and the lesson note scroll independently; neither hijacks the other's scroll.",
      behaviour: ["No scroll coupling", "Canvas keeps its own viewport"],
      implementation: { files: ["src/pages/NotebookEditorPage.tsx", "src/components/lessonnotes/SlidePanel.tsx"] },
      validation: [{ kind: "behaviour", target: "Scroll the canvas and confirm the note does not move" }],
      restorationSource: "independent scrolling fix (current)",
      status: "PASS",
      permanent: "PENDING",
    },
    {
      id: "SLD-003",
      name: "Slide capture, screenshot, image and video import",
      category: "Slides",
      source: "Approved: 'COMPLETE SLIDE CAPTURE, SCREENSHOT, IMAGE & VIDEO IMPORT'",
      requirement: "A slide can take a capture/screenshot of note or board content and import images and video from device or GPL assets.",
      behaviour: ["Capture is faithful", "Import offers device and GPL assets"],
      implementation: { files: ["src/components/lessonnotes/SlidePanel.tsx", "src/components/assets/MyGplMediaPicker.tsx"] },
      dependencies: ["DIAG-007", "AST-004"],
      validation: [{ kind: "behaviour", target: "Import a video from GPL assets into a slide" }],
      restorationSource: "current slide panel import paths",
      status: "PASS",
      permanent: "PENDING",
    },
  ],
};
